/* Generated by itemis CREATE code generator. */
package smarthub.java;

import com.yakindu.core.IEventDriven;
import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class GarageDoor_Unit implements ITimed, IEventDriven {
	public static class System {
		private GarageDoor_Unit parent;
		
		public System(GarageDoor_Unit parent) {
			this.parent = parent;
		}
		private boolean on;
		
		
		public void raiseOn() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					on = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean off;
		
		
		public void raiseOff() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					off = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean isOn;
		
		public synchronized boolean getIsOn() {
			synchronized(parent) {
				return isOn;
			}
		}
		
		public void setIsOn(boolean value) {
			synchronized(parent) {
				this.isOn = value;
			}
		}
		
		private String door_status;
		
		public synchronized String getDoor_status() {
			synchronized(parent) {
				return door_status;
			}
		}
		
		public void setDoor_status(String value) {
			synchronized(parent) {
				this.door_status = value;
			}
		}
		
	}
	
	public static class Door {
		private GarageDoor_Unit parent;
		
		public Door(GarageDoor_Unit parent) {
			this.parent = parent;
		}
		private boolean opened;
		
		
		public void raiseOpened() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					opened = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean closed;
		
		
		public void raiseClosed() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					closed = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean re_open;
		
		
		public void raiseRe_open() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					re_open = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean open_door;
		
		
		public void raiseOpen_door() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					open_door = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean close_door;
		
		
		public void raiseClose_door() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					close_door = true;
				});
				parent.runCycle();
			}
		}
		
		private long open_time;
		
		public synchronized long getOpen_time() {
			synchronized(parent) {
				return open_time;
			}
		}
		
		public void setOpen_time(long value) {
			synchronized(parent) {
				this.open_time = value;
			}
		}
		
		private long current_open_time;
		
		public synchronized long getCurrent_open_time() {
			synchronized(parent) {
				return current_open_time;
			}
		}
		
		public void setCurrent_open_time(long value) {
			synchronized(parent) {
				this.current_open_time = value;
			}
		}
		
		private long auto_timeout;
		
		public synchronized long getAuto_timeout() {
			synchronized(parent) {
				return auto_timeout;
			}
		}
		
		public void setAuto_timeout(long value) {
			synchronized(parent) {
				this.auto_timeout = value;
			}
		}
		
		private boolean block;
		
		public synchronized boolean getBlock() {
			synchronized(parent) {
				return block;
			}
		}
		
		public void setBlock(boolean value) {
			synchronized(parent) {
				this.block = value;
			}
		}
		
		private boolean door_closed;
		
		public synchronized boolean getDoor_closed() {
			synchronized(parent) {
				return door_closed;
			}
		}
		
		public void setDoor_closed(boolean value) {
			synchronized(parent) {
				this.door_closed = value;
			}
		}
		
	}
	
	protected System system;
	
	protected Door door;
	
	public enum State {
		_GARAGEDOOR_UNIT__DOORINUSE,
		_GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSED,
		_GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENING,
		_GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENED,
		_GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING,
		_GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__NO_BLOCK,
		_GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__BLOCK,
		_GARAGEDOOR_UNIT__DOOROFF,
		$NULLSTATE$
	};
	
	private State[] historyVector = new State[1];
	private final State[] stateVector = new State[1];
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[6];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		synchronized(GarageDoor_Unit.this) {
			return isExecuting;
		}
	}
	
	protected void setIsExecuting(boolean value) {
		synchronized(GarageDoor_Unit.this) {
			this.isExecuting = value;
		}
	}
	public GarageDoor_Unit() {
		system = new System(this);
		door = new Door(this);
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		for (int i = 0; i < 1; i++) {
			historyVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		/* Default init sequence for statechart GarageDoor_Unit */
		system.setIsOn(false);
		system.setDoor_status("Door Closed");
		door.setOpen_time(30l);
		door.setCurrent_open_time(0l);
		door.setAuto_timeout(50l);
		door.setBlock(false);
		door.setDoor_closed(true);
		
		isExecuting = false;
	}
	
	public synchronized void enter() {
		/* Activates the state machine. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		/* Default enter sequence for statechart GarageDoor_Unit */
		enterSequence__GarageDoor_Unit__default();
		isExecuting = false;
	}
	
	public synchronized void exit() {
		/* Deactivates the state machine. */
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		/* Default exit sequence for statechart GarageDoor_Unit */
		exitSequence__GarageDoor_Unit_();
		stateVector[0] = State.$NULLSTATE$;
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	private void clearInEvents() {
		system.on = false;
		system.off = false;
		door.opened = false;
		door.closed = false;
		door.re_open = false;
		door.open_door = false;
		door.close_door = false;
		timeEvents[0] = false;
		timeEvents[1] = false;
		timeEvents[2] = false;
		timeEvents[3] = false;
		timeEvents[4] = false;
		timeEvents[5] = false;
	}
	
	private void microStep() {
		switch (stateVector[0]) {
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSED:
			_GarageDoor_Unit__doorInUse__Door_Working__door_closed_react(-1l);
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENING:
			_GarageDoor_Unit__doorInUse__Door_Working__door_opening_react(-1l);
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENED:
			_GarageDoor_Unit__doorInUse__Door_Working__door_opened_react(-1l);
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__NO_BLOCK:
			_GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block_react(-1l);
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__BLOCK:
			_GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__block_react(-1l);
			break;
		case _GARAGEDOOR_UNIT__DOOROFF:
			_GarageDoor_Unit__doorOff_react(-1l);
			break;
		default:
			break;
		}
	}
	
	private void runCycle() {
		/* Performs a 'run to completion' step. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		nextEvent();
		do { 
			microStep();
			clearInEvents();
		} while (nextEvent());
		isExecuting = false;
	}
	
	protected boolean nextEvent() {
		if(!inEventQueue.isEmpty()) {
			inEventQueue.poll().run();
			return true;
		}
		return false;
	}
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case _GARAGEDOOR_UNIT__DOORINUSE:
			return stateVector[0].ordinal() >= State.
					_GARAGEDOOR_UNIT__DOORINUSE.ordinal()&& stateVector[0].ordinal() <= State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__BLOCK.ordinal();
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSED:
			return stateVector[0] == State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSED;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENING:
			return stateVector[0] == State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENING;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENED:
			return stateVector[0] == State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENED;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING:
			return stateVector[0].ordinal() >= State.
					_GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING.ordinal()&& stateVector[0].ordinal() <= State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__BLOCK.ordinal();
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__NO_BLOCK:
			return stateVector[0] == State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__NO_BLOCK;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__BLOCK:
			return stateVector[0] == State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__BLOCK;
		case _GARAGEDOOR_UNIT__DOOROFF:
			return stateVector[0] == State._GARAGEDOOR_UNIT__DOOROFF;
		default:
			return false;
		}
	}
	
	public synchronized void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public synchronized void raiseTimeEvent(int eventID) {
		inEventQueue.add(() -> {
			timeEvents[eventID] = true;
		});
		runCycle();
	}
	
	public System system() {
		return system;
	}
	
	public Door door() {
		return door;
	}
	
	
	/* Entry action for state 'doorInUse'. */
	private void entryAction__GarageDoor_Unit__doorInUse() {
		/* Entry action for state 'doorInUse'. */
		timerService.setTimer(this, 0, 500l, true);
		system.setIsOn(true);
	}
	
	/* Entry action for state 'door_closed'. */
	private void entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_closed() {
		/* Entry action for state 'door_closed'. */
		timerService.setTimer(this, 1, (door.getAuto_timeout() * 1000l), false);
		door.setCurrent_open_time(0l);
		door.setDoor_closed(true);
		system.setDoor_status("Door Closed");
	}
	
	/* Entry action for state 'door_opening'. */
	private void entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_opening() {
		/* Entry action for state 'door_opening'. */
		timerService.setTimer(this, 2, (1l * 1000l), true);
		door.setCurrent_open_time(door.getCurrent_open_time() + 1l);
		system.setDoor_status("Door Opening");
	}
	
	/* Entry action for state 'door_opened'. */
	private void entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_opened() {
		/* Entry action for state 'door_opened'. */
		timerService.setTimer(this, 3, (door.getAuto_timeout() * 1000l), false);
		door.setCurrent_open_time(door.open_time);
		system.setDoor_status("Door Opened");
	}
	
	/* Entry action for state 'door_closing'. */
	private void entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing() {
		/* Entry action for state 'door_closing'. */
		timerService.setTimer(this, 4, (1l * 1000l), true);
		door.setCurrent_open_time(door.getCurrent_open_time() - 1l);
		system.setDoor_status("Door Closing");
	}
	
	/* Entry action for state 'no_block'. */
	private void entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block() {
		/* Entry action for state 'no_block'. */
		timerService.setTimer(this, 5, 100l, true);
		door.setBlock(false);
	}
	
	/* Entry action for state 'block'. */
	private void entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__block() {
		/* Entry action for state 'block'. */
		door.raiseRe_open();
	}
	
	/* Entry action for state 'doorOff'. */
	private void entryAction__GarageDoor_Unit__doorOff() {
		/* Entry action for state 'doorOff'. */
		system.setIsOn(false);
	}
	
	/* Exit action for state 'doorInUse'. */
	private void exitAction__GarageDoor_Unit__doorInUse() {
		/* Exit action for state 'doorInUse'. */
		timerService.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'door_closed'. */
	private void exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_closed() {
		/* Exit action for state 'door_closed'. */
		timerService.unsetTimer(this, 1);
		door.setDoor_closed(false);
	}
	
	/* Exit action for state 'door_opening'. */
	private void exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_opening() {
		/* Exit action for state 'door_opening'. */
		timerService.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'door_opened'. */
	private void exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_opened() {
		/* Exit action for state 'door_opened'. */
		timerService.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'door_closing'. */
	private void exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing() {
		/* Exit action for state 'door_closing'. */
		timerService.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'no_block'. */
	private void exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block() {
		/* Exit action for state 'no_block'. */
		timerService.unsetTimer(this, 5);
	}
	
	/* 'default' enter sequence for state doorInUse */
	private void enterSequence__GarageDoor_Unit__doorInUse_default() {
		/* 'default' enter sequence for state doorInUse */
		entryAction__GarageDoor_Unit__doorInUse();
		enterSequence__GarageDoor_Unit__doorInUse__Door_Working__default();
	}
	
	/* 'default' enter sequence for state door_closed */
	private void enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closed_default() {
		/* 'default' enter sequence for state door_closed */
		entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_closed();
		stateVector[0] = State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSED;
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state door_opening */
	private void enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opening_default() {
		/* 'default' enter sequence for state door_opening */
		entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_opening();
		stateVector[0] = State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENING;
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state door_opened */
	private void enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opened_default() {
		/* 'default' enter sequence for state door_opened */
		entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_opened();
		stateVector[0] = State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENED;
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state door_closing */
	private void enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing_default() {
		/* 'default' enter sequence for state door_closing */
		entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing();
		enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__default();
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state no_block */
	private void enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block_default() {
		/* 'default' enter sequence for state no_block */
		entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block();
		stateVector[0] = State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__NO_BLOCK;
	}
	
	/* 'default' enter sequence for state block */
	private void enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__block_default() {
		/* 'default' enter sequence for state block */
		entryAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__block();
		stateVector[0] = State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__BLOCK;
	}
	
	/* 'default' enter sequence for state doorOff */
	private void enterSequence__GarageDoor_Unit__doorOff_default() {
		/* 'default' enter sequence for state doorOff */
		entryAction__GarageDoor_Unit__doorOff();
		stateVector[0] = State._GARAGEDOOR_UNIT__DOOROFF;
	}
	
	/* 'default' enter sequence for region <GarageDoor_Unit> */
	private void enterSequence__GarageDoor_Unit__default() {
		/* 'default' enter sequence for region <GarageDoor_Unit> */
		react__GarageDoor_Unit___entry_Default();
	}
	
	/* 'default' enter sequence for region <Door_Working> */
	private void enterSequence__GarageDoor_Unit__doorInUse__Door_Working__default() {
		/* 'default' enter sequence for region <Door_Working> */
		react__GarageDoor_Unit__doorInUse__Door_Working___entry_Default();
	}
	
	/* shallow enterSequence with history in child <Door_Working> */
	private void shallowEnterSequence__GarageDoor_Unit__doorInUse__Door_Working_() {
		/* shallow enterSequence with history in child <Door_Working> */
		switch (historyVector[0]) {
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSED:
			enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closed_default();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENING:
			enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opening_default();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENED:
			enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opened_default();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__NO_BLOCK:
			enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing_default();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__BLOCK:
			enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing_default();
			break;
		default:
			break;
		}
	}
	
	/* 'default' enter sequence for region <Block_Status> */
	private void enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__default() {
		/* 'default' enter sequence for region <Block_Status> */
		react__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status___entry_Default();
	}
	
	/* Default exit sequence for state doorInUse */
	private void exitSequence__GarageDoor_Unit__doorInUse() {
		/* Default exit sequence for state doorInUse */
		exitSequence__GarageDoor_Unit__doorInUse__Door_Working_();
		stateVector[0] = State.$NULLSTATE$;
		exitAction__GarageDoor_Unit__doorInUse();
	}
	
	/* Default exit sequence for state door_closed */
	private void exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closed() {
		/* Default exit sequence for state door_closed */
		stateVector[0] = State._GARAGEDOOR_UNIT__DOORINUSE;
		exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_closed();
	}
	
	/* Default exit sequence for state door_opening */
	private void exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opening() {
		/* Default exit sequence for state door_opening */
		stateVector[0] = State._GARAGEDOOR_UNIT__DOORINUSE;
		exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_opening();
	}
	
	/* Default exit sequence for state door_opened */
	private void exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opened() {
		/* Default exit sequence for state door_opened */
		stateVector[0] = State._GARAGEDOOR_UNIT__DOORINUSE;
		exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_opened();
	}
	
	/* Default exit sequence for state door_closing */
	private void exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing() {
		/* Default exit sequence for state door_closing */
		exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status_();
		stateVector[0] = State._GARAGEDOOR_UNIT__DOORINUSE;
		exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing();
	}
	
	/* Default exit sequence for state no_block */
	private void exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block() {
		/* Default exit sequence for state no_block */
		stateVector[0] = State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING;
		exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block();
	}
	
	/* Default exit sequence for state block */
	private void exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__block() {
		/* Default exit sequence for state block */
		stateVector[0] = State._GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING;
	}
	
	/* Default exit sequence for state doorOff */
	private void exitSequence__GarageDoor_Unit__doorOff() {
		/* Default exit sequence for state doorOff */
		stateVector[0] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for region <GarageDoor_Unit> */
	private void exitSequence__GarageDoor_Unit_() {
		/* Default exit sequence for region <GarageDoor_Unit> */
		switch (stateVector[0]) {
		case _GARAGEDOOR_UNIT__DOORINUSE:
			exitSequence__GarageDoor_Unit__doorInUse();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSED:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closed();
			exitAction__GarageDoor_Unit__doorInUse();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENING:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opening();
			exitAction__GarageDoor_Unit__doorInUse();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENED:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opened();
			exitAction__GarageDoor_Unit__doorInUse();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing();
			exitAction__GarageDoor_Unit__doorInUse();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__NO_BLOCK:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block();
			exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing();
			exitAction__GarageDoor_Unit__doorInUse();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__BLOCK:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__block();
			exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing();
			exitAction__GarageDoor_Unit__doorInUse();
			break;
		case _GARAGEDOOR_UNIT__DOOROFF:
			exitSequence__GarageDoor_Unit__doorOff();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region <Door_Working> */
	private void exitSequence__GarageDoor_Unit__doorInUse__Door_Working_() {
		/* Default exit sequence for region <Door_Working> */
		switch (stateVector[0]) {
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSED:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closed();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENING:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opening();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_OPENED:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opened();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__NO_BLOCK:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block();
			exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__BLOCK:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__block();
			exitAction__GarageDoor_Unit__doorInUse__Door_Working__door_closing();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region <Block_Status> */
	private void exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status_() {
		/* Default exit sequence for region <Block_Status> */
		switch (stateVector[0]) {
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__NO_BLOCK:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block();
			break;
		case _GARAGEDOOR_UNIT__DOORINUSE__DOOR_WORKING__DOOR_CLOSING__BLOCK_STATUS__BLOCK:
			exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__block();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react__GarageDoor_Unit___entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__GarageDoor_Unit__doorOff_default();
	}
	
	/* Default react sequence for shallow history entry  */
	private void react__GarageDoor_Unit__doorInUse__Door_Working___entry_Default() {
		/* Default react sequence for shallow history entry  */
		/* Enter the region with shallow history */
		if (historyVector[0] != State.$NULLSTATE$) {
			shallowEnterSequence__GarageDoor_Unit__doorInUse__Door_Working_();
		} else {
			enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closed_default();
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status___entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block_default();
	}
	
	private long _GarageDoor_Unit__doorInUse_react(long transitioned_before) {
		/* The reactions of state doorInUse. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (((timeEvents[0]) && (!(system.getIsOn())))) {
				exitSequence__GarageDoor_Unit__doorInUse();
				timeEvents[0] = false;
				enterSequence__GarageDoor_Unit__doorOff_default();
				transitioned_after = 0l;
			} else {
				if (system.off) {
					exitSequence__GarageDoor_Unit__doorInUse();
					enterSequence__GarageDoor_Unit__doorOff_default();
					transitioned_after = 0l;
				}
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		}
		return transitioned_after;
	}
	
	private long _GarageDoor_Unit__doorInUse__Door_Working__door_closed_react(long transitioned_before) {
		/* The reactions of state door_closed. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (door.open_door) {
				exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closed();
				enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opening_default();
				_GarageDoor_Unit__doorInUse_react(0l);
				transitioned_after = 0l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			if (timeEvents[1]) {
				system.setIsOn(false);
			}
			transitioned_after = _GarageDoor_Unit__doorInUse_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _GarageDoor_Unit__doorInUse__Door_Working__door_opening_react(long transitioned_before) {
		/* The reactions of state door_opening. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (door.opened) {
				exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opening();
				enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opened_default();
				_GarageDoor_Unit__doorInUse_react(0l);
				transitioned_after = 0l;
			} else {
				if (timeEvents[2]) {
					exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opening();
					timeEvents[2] = false;
					enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opening_default();
					_GarageDoor_Unit__doorInUse_react(0l);
					transitioned_after = 0l;
				}
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			if (door.getCurrent_open_time()>=door.getOpen_time()) {
				door.raiseOpened();
			}
			transitioned_after = _GarageDoor_Unit__doorInUse_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _GarageDoor_Unit__doorInUse__Door_Working__door_opened_react(long transitioned_before) {
		/* The reactions of state door_opened. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (door.close_door) {
				exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opened();
				enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing_default();
				_GarageDoor_Unit__doorInUse_react(0l);
				transitioned_after = 0l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			if (timeEvents[3]) {
				door.raiseClose_door();
			}
			transitioned_after = _GarageDoor_Unit__doorInUse_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _GarageDoor_Unit__doorInUse__Door_Working__door_closing_react(long transitioned_before) {
		/* The reactions of state door_closing. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (door.closed) {
				exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing();
				enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closed_default();
				_GarageDoor_Unit__doorInUse_react(0l);
				transitioned_after = 0l;
			} else {
				if (door.re_open) {
					exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing();
					enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_opening_default();
					_GarageDoor_Unit__doorInUse_react(0l);
					transitioned_after = 0l;
				} else {
					if (timeEvents[4]) {
						exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing();
						timeEvents[4] = false;
						enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing_default();
						_GarageDoor_Unit__doorInUse_react(0l);
						transitioned_after = 0l;
					}
				}
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			if (door.getCurrent_open_time()<=0l) {
				door.raiseClosed();
			}
			transitioned_after = _GarageDoor_Unit__doorInUse_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block_react(long transitioned_before) {
		/* The reactions of state no_block. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (((timeEvents[5]) && (door.getBlock()))) {
				exitSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__no_block();
				timeEvents[5] = false;
				enterSequence__GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__block_default();
				_GarageDoor_Unit__doorInUse__Door_Working__door_closing_react(0l);
				transitioned_after = 0l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = _GarageDoor_Unit__doorInUse__Door_Working__door_closing_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _GarageDoor_Unit__doorInUse__Door_Working__door_closing__Block_Status__block_react(long transitioned_before) {
		/* The reactions of state block. */
		long transitioned_after = transitioned_before;
		/* Always execute local reactions. */
		transitioned_after = _GarageDoor_Unit__doorInUse__Door_Working__door_closing_react(transitioned_before);
		return transitioned_after;
	}
	
	private long _GarageDoor_Unit__doorOff_react(long transitioned_before) {
		/* The reactions of state doorOff. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (system.on) {
				exitSequence__GarageDoor_Unit__doorOff();
				enterSequence__GarageDoor_Unit__doorInUse_default();
				transitioned_after = 0l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		}
		return transitioned_after;
	}
	
	/* Can be used by the client code to trigger a run to completion step without raising an event. */
	public synchronized void triggerWithoutEvent() {
		runCycle();
	}
}
