/* Generated by itemis CREATE code generator. */
package smarthub.java;

import com.yakindu.core.IEventDriven;
import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import smarthub.java.Actuator_Component_2;
import smarthub.java.Controller_Component_2;
import smarthub.java.DeviceTemp_Component;
import smarthub.java.GarageDoor_Unit;
import smarthub.java.Network_Component;
import smarthub.java.Power_Component;
import smarthub.java.Ultrasonic_MotionDetector;
import smarthub.java.Ultrasonic_Sensor;

public class SmartGarageDoorSystem implements ITimed, IEventDriven {
	public static class System {
		private SmartGarageDoorSystem parent;
		
		public System(SmartGarageDoorSystem parent) {
			this.parent = parent;
		}
		private boolean on;
		
		
		public void raiseOn() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					on = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean off;
		
		
		public void raiseOff() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					off = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean connect_network;
		
		
		public void raiseConnect_network() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					connect_network = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean disconnect_network;
		
		
		public void raiseDisconnect_network() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					disconnect_network = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean active_actuator;
		
		
		public void raiseActive_actuator() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					active_actuator = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean deactive_actuator;
		
		
		public void raiseDeactive_actuator() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					deactive_actuator = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean isOn;
		
		public synchronized boolean getIsOn() {
			synchronized(parent) {
				return isOn;
			}
		}
		
		public void setIsOn(boolean value) {
			synchronized(parent) {
				this.isOn = value;
			}
		}
		
	}
	
	public static class SensorInput {
		private SmartGarageDoorSystem parent;
		
		public SensorInput(SmartGarageDoorSystem parent) {
			this.parent = parent;
		}
		private long detection_time;
		
		public synchronized long getDetection_time() {
			synchronized(parent) {
				return detection_time;
			}
		}
		
		public void setDetection_time(long value) {
			synchronized(parent) {
				this.detection_time = value;
			}
		}
		
		private long timeout_time;
		
		public synchronized long getTimeout_time() {
			synchronized(parent) {
				return timeout_time;
			}
		}
		
		public void setTimeout_time(long value) {
			synchronized(parent) {
				this.timeout_time = value;
			}
		}
		
	}
	
	public static class SensorOutput {
		private SmartGarageDoorSystem parent;
		
		public SensorOutput(SmartGarageDoorSystem parent) {
			this.parent = parent;
		}
		private boolean activity;
		
		public synchronized boolean getActivity() {
			synchronized(parent) {
				return activity;
			}
		}
		
		public void setActivity(boolean value) {
			synchronized(parent) {
				this.activity = value;
			}
		}
		
		private long counter;
		
		public synchronized long getCounter() {
			synchronized(parent) {
				return counter;
			}
		}
		
		public void setCounter(long value) {
			synchronized(parent) {
				this.counter = value;
			}
		}
		
	}
	
	protected System system;
	
	protected SensorInput sensorInput;
	
	protected SensorOutput sensorOutput;
	
	public enum State {
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_OFF,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_ON,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__ACTUATOR_STANDBY,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__CLOSE,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__OPEN,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_OFF,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__CONTROLLER_PROCESSING,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__STANDBY,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_OFF,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON__SENSOR_MONITORING__SENSOR_COMPONENT,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_OFF,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT__RECEIVING_NETWORK_CONNECTION_UPDATES__NETWORK_COMPONENT,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_OFF,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT__RECEIVING_UPDATES_FROM_POWER_COMPONENT__POWER_CONSUMPTION_UPDATES,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_OFF,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT__RECEIVING_UPDATES_FROM_DEVICETEMP_COMPONENT__TEMPERATURE_UPDATES,
		SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_OFF,
		$NULLSTATE$
	};
	
	private final State[] stateVector = new State[7];
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[6];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		synchronized(SmartGarageDoorSystem.this) {
			return isExecuting;
		}
	}
	
	protected void setIsExecuting(boolean value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.isExecuting = value;
		}
	}
	private long stateConfVectorPosition;
	
	protected long getStateConfVectorPosition() {
		synchronized(SmartGarageDoorSystem.this) {
			return stateConfVectorPosition;
		}
	}
	
	protected void setStateConfVectorPosition(long value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.stateConfVectorPosition = value;
		}
	}
	public SmartGarageDoorSystem() {
		system = new System(this);
		sensorInput = new SensorInput(this);
		sensorOutput = new SensorOutput(this);
		for (int i = 0; i < 7; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		/* Default init sequence for statechart SmartGarageDoorSystem */
		setActuator(null);
		setController(null);
		setSensor(null);
		setWiFi(null);
		setPower(null);
		setTemp(null);
		setGarageDoor(null);
		setMessage("");
		setWiFi_connection(false);
		setTemp_value(50l);
		setPower_input(10l);
		setPower_total(0l);
		setPower_required(10l);
		system.setIsOn(false);
		sensorInput.setDetection_time(0l);
		sensorInput.setTimeout_time(0l);
		sensorOutput.setActivity(false);
		sensorOutput.setCounter(0l);
		
		isExecuting = false;
	}
	
	public synchronized void enter() {
		/* Activates the state machine. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		/* Default enter sequence for statechart SmartGarageDoorSystem */
		enterSequence_SmartGarageDoorSystem_default();
		isExecuting = false;
	}
	
	public synchronized void exit() {
		/* Deactivates the state machine. */
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		/* Default exit sequence for statechart SmartGarageDoorSystem */
		exitSequence_SmartGarageDoorSystem();
		stateVector[0] = State.$NULLSTATE$;
		stateVector[1] = State.$NULLSTATE$;
		stateVector[2] = State.$NULLSTATE$;
		stateVector[3] = State.$NULLSTATE$;
		stateVector[4] = State.$NULLSTATE$;
		stateVector[5] = State.$NULLSTATE$;
		stateVector[6] = State.$NULLSTATE$;
		stateConfVectorPosition = 6;
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$||stateVector[1] != State.$NULLSTATE$||stateVector[2] != State.$NULLSTATE$||stateVector[3] != State.$NULLSTATE$||stateVector[4] != State.$NULLSTATE$||stateVector[5] != State.$NULLSTATE$||stateVector[6] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	private void clearInEvents() {
		active_controller = false;
		system.on = false;
		system.off = false;
		system.connect_network = false;
		system.disconnect_network = false;
		system.active_actuator = false;
		system.deactive_actuator = false;
		timeEvents[0] = false;
		timeEvents[1] = false;
		timeEvents[2] = false;
		timeEvents[3] = false;
		timeEvents[4] = false;
		timeEvents[5] = false;
	}
	
	private void microStep() {
		long transitioned = -1l;
		stateConfVectorPosition = 0l;
		switch (stateVector[0]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_OFF:
			transitioned = smartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_off_react(transitioned);
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_ON:
			transitioned = smartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on_react(transitioned);
			break;
		default:
			break;
		}
		if (getStateConfVectorPosition()<1l) {
			switch (stateVector[1]) {
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__ACTUATOR_STANDBY:
				transitioned = smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Actuator_Standby_react(transitioned);
				break;
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__CLOSE:
				transitioned = smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Close_react(transitioned);
				break;
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__OPEN:
				transitioned = smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Open_react(transitioned);
				break;
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_OFF:
				transitioned = smartGarageDoorSystem_IoT_Template_ActuatorComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<2l) {
			switch (stateVector[2]) {
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__CONTROLLER_PROCESSING:
				transitioned = smartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Controller_Processing_react(transitioned);
				break;
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__STANDBY:
				transitioned = smartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby_react(transitioned);
				break;
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_OFF:
				transitioned = smartGarageDoorSystem_IoT_Template_ControllerComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<3l) {
			switch (stateVector[3]) {
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON__SENSOR_MONITORING__SENSOR_COMPONENT:
				transitioned = smartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component_react(transitioned);
				break;
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_OFF:
				transitioned = smartGarageDoorSystem_IoT_Template_SensorComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<4l) {
			switch (stateVector[4]) {
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT__RECEIVING_NETWORK_CONNECTION_UPDATES__NETWORK_COMPONENT:
				transitioned = smartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component_react(transitioned);
				break;
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_OFF:
				transitioned = smartGarageDoorSystem_IoT_Template_NetworkComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<5l) {
			switch (stateVector[5]) {
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT__RECEIVING_UPDATES_FROM_POWER_COMPONENT__POWER_CONSUMPTION_UPDATES:
				transitioned = smartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates_react(transitioned);
				break;
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_OFF:
				transitioned = smartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<6l) {
			switch (stateVector[6]) {
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT__RECEIVING_UPDATES_FROM_DEVICETEMP_COMPONENT__TEMPERATURE_UPDATES:
				smartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates_react(transitioned);
				break;
			case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_OFF:
				smartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_off_react(transitioned);
				break;
			default:
				break;
			}
		}
	}
	
	private void runCycle() {
		/* Performs a 'run to completion' step. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		nextEvent();
		do { 
			microStep();
			clearInEvents();
		} while (nextEvent());
		isExecuting = false;
	}
	
	protected boolean nextEvent() {
		if(!inEventQueue.isEmpty()) {
			inEventQueue.poll().run();
			return true;
		}
		return false;
	}
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE:
			return stateVector[0].ordinal() >= State.
					SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE.ordinal()&& stateVector[0].ordinal() <= State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_OFF.ordinal();
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_OFF:
			return stateVector[0] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_OFF;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_ON:
			return stateVector[0] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_ON;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON:
			return stateVector[1].ordinal() >= State.
					SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON.ordinal()&& stateVector[1].ordinal() <= State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__OPEN.ordinal();
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__ACTUATOR_STANDBY:
			return stateVector[1] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__ACTUATOR_STANDBY;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__CLOSE:
			return stateVector[1] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__CLOSE;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__OPEN:
			return stateVector[1] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__OPEN;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_OFF:
			return stateVector[1] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_OFF;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON:
			return stateVector[2].ordinal() >= State.
					SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON.ordinal()&& stateVector[2].ordinal() <= State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__STANDBY.ordinal();
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__CONTROLLER_PROCESSING:
			return stateVector[2] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__CONTROLLER_PROCESSING;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__STANDBY:
			return stateVector[2] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__STANDBY;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_OFF:
			return stateVector[2] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_OFF;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON:
			return stateVector[3].ordinal() >= State.
					SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON.ordinal()&& stateVector[3].ordinal() <= State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON__SENSOR_MONITORING__SENSOR_COMPONENT.ordinal();
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON__SENSOR_MONITORING__SENSOR_COMPONENT:
			return stateVector[3] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON__SENSOR_MONITORING__SENSOR_COMPONENT;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_OFF:
			return stateVector[3] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_OFF;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT:
			return stateVector[4].ordinal() >= State.
					SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT.ordinal()&& stateVector[4].ordinal() <= State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT__RECEIVING_NETWORK_CONNECTION_UPDATES__NETWORK_COMPONENT.ordinal();
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT__RECEIVING_NETWORK_CONNECTION_UPDATES__NETWORK_COMPONENT:
			return stateVector[4] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT__RECEIVING_NETWORK_CONNECTION_UPDATES__NETWORK_COMPONENT;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_OFF:
			return stateVector[4] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_OFF;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT:
			return stateVector[5].ordinal() >= State.
					SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT.ordinal()&& stateVector[5].ordinal() <= State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT__RECEIVING_UPDATES_FROM_POWER_COMPONENT__POWER_CONSUMPTION_UPDATES.ordinal();
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT__RECEIVING_UPDATES_FROM_POWER_COMPONENT__POWER_CONSUMPTION_UPDATES:
			return stateVector[5] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT__RECEIVING_UPDATES_FROM_POWER_COMPONENT__POWER_CONSUMPTION_UPDATES;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_OFF:
			return stateVector[5] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_OFF;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT:
			return stateVector[6].ordinal() >= State.
					SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT.ordinal()&& stateVector[6].ordinal() <= State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT__RECEIVING_UPDATES_FROM_DEVICETEMP_COMPONENT__TEMPERATURE_UPDATES.ordinal();
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT__RECEIVING_UPDATES_FROM_DEVICETEMP_COMPONENT__TEMPERATURE_UPDATES:
			return stateVector[6] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT__RECEIVING_UPDATES_FROM_DEVICETEMP_COMPONENT__TEMPERATURE_UPDATES;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_OFF:
			return stateVector[6] == State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_OFF;
		default:
			return false;
		}
	}
	
	public synchronized void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public synchronized void raiseTimeEvent(int eventID) {
		inEventQueue.add(() -> {
			timeEvents[eventID] = true;
		});
		runCycle();
	}
	
	public System system() {
		return system;
	}
	
	public SensorInput sensorInput() {
		return sensorInput;
	}
	
	public SensorOutput sensorOutput() {
		return sensorOutput;
	}
	
	
	private boolean active_controller;
	
	
	public void raiseActive_controller() {
		synchronized(SmartGarageDoorSystem.this) {
			inEventQueue.add(() -> {
				active_controller = true;
			});
			runCycle();
		}
	}
	
	private Actuator_Component_2 actuator;
	
	public synchronized Actuator_Component_2 getActuator() {
		synchronized(SmartGarageDoorSystem.this) {
			return actuator;
		}
	}
	
	public void setActuator(Actuator_Component_2 value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.actuator = value;
		}
	}
	
	private Controller_Component_2 controller;
	
	public synchronized Controller_Component_2 getController() {
		synchronized(SmartGarageDoorSystem.this) {
			return controller;
		}
	}
	
	public void setController(Controller_Component_2 value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.controller = value;
		}
	}
	
	private Ultrasonic_MotionDetector sensor;
	
	public synchronized Ultrasonic_MotionDetector getSensor() {
		synchronized(SmartGarageDoorSystem.this) {
			return sensor;
		}
	}
	
	public void setSensor(Ultrasonic_MotionDetector value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.sensor = value;
		}
	}
	
	private Network_Component wiFi;
	
	public synchronized Network_Component getWiFi() {
		synchronized(SmartGarageDoorSystem.this) {
			return wiFi;
		}
	}
	
	public void setWiFi(Network_Component value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.wiFi = value;
		}
	}
	
	private Power_Component power;
	
	public synchronized Power_Component getPower() {
		synchronized(SmartGarageDoorSystem.this) {
			return power;
		}
	}
	
	public void setPower(Power_Component value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.power = value;
		}
	}
	
	private DeviceTemp_Component temp;
	
	public synchronized DeviceTemp_Component getTemp() {
		synchronized(SmartGarageDoorSystem.this) {
			return temp;
		}
	}
	
	public void setTemp(DeviceTemp_Component value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.temp = value;
		}
	}
	
	private GarageDoor_Unit garageDoor;
	
	public synchronized GarageDoor_Unit getGarageDoor() {
		synchronized(SmartGarageDoorSystem.this) {
			return garageDoor;
		}
	}
	
	public void setGarageDoor(GarageDoor_Unit value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.garageDoor = value;
		}
	}
	
	private String message;
	
	public synchronized String getMessage() {
		synchronized(SmartGarageDoorSystem.this) {
			return message;
		}
	}
	
	public void setMessage(String value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.message = value;
		}
	}
	
	private boolean wiFi_connection;
	
	public synchronized boolean getWiFi_connection() {
		synchronized(SmartGarageDoorSystem.this) {
			return wiFi_connection;
		}
	}
	
	public void setWiFi_connection(boolean value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.wiFi_connection = value;
		}
	}
	
	private long temp_value;
	
	public synchronized long getTemp_value() {
		synchronized(SmartGarageDoorSystem.this) {
			return temp_value;
		}
	}
	
	public void setTemp_value(long value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.temp_value = value;
		}
	}
	
	private long power_input;
	
	public synchronized long getPower_input() {
		synchronized(SmartGarageDoorSystem.this) {
			return power_input;
		}
	}
	
	public void setPower_input(long value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.power_input = value;
		}
	}
	
	private long power_total;
	
	public synchronized long getPower_total() {
		synchronized(SmartGarageDoorSystem.this) {
			return power_total;
		}
	}
	
	public void setPower_total(long value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.power_total = value;
		}
	}
	
	private long power_required;
	
	public synchronized long getPower_required() {
		synchronized(SmartGarageDoorSystem.this) {
			return power_required;
		}
	}
	
	public void setPower_required(long value) {
		synchronized(SmartGarageDoorSystem.this) {
			this.power_required = value;
		}
	}
	
	/* Entry action for state 'off'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_off() {
		/* Entry action for state 'off'. */
		system.setIsOn(false);
		system.raiseConnect_network();
		getPower().raiseOff();
		getSensor().raiseOff();
	}
	
	/* Entry action for state 'on'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on() {
		/* Entry action for state 'on'. */
		timerService.setTimer(this, 0, 500l, false);
		system.setIsOn(true);
		getPower().raiseOn();
		getSensor().raiseOn();
	}
	
	/* Entry action for state 'Actuator_isON'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON() {
		/* Entry action for state 'Actuator_isON'. */
		setMessage("Smart Garage Door main function is here");
		getActuator().raiseOn();
	}
	
	/* Entry action for state 'Close'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Close() {
		/* Entry action for state 'Close'. */
		getGarageDoor().system().raiseOn();
		getGarageDoor().door().raiseClose_door();
		system.raiseDeactive_actuator();
		actuator.device().setFunctionFinished(true);
	}
	
	/* Entry action for state 'Open'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Open() {
		/* Entry action for state 'Open'. */
		getGarageDoor().system().raiseOn();
		getGarageDoor().door().raiseOpen_door();
		system.raiseDeactive_actuator();
		actuator.device().setFunctionFinished(true);
	}
	
	/* Entry action for state 'off'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_off() {
		/* Entry action for state 'off'. */
		getActuator().raiseOff();
		getGarageDoor().system().raiseOff();
	}
	
	/* Entry action for state 'Controller_Component_isON'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON() {
		/* Entry action for state 'Controller_Component_isON'. */
		getController().raiseOn();
	}
	
	/* Entry action for state 'Controller_Processing'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Controller_Processing() {
		/* Entry action for state 'Controller_Processing'. */
		getController().raiseTrigger_controller();
		actuator.device().setFunctionFinished(false);
	}
	
	/* Entry action for state 'Standby'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby() {
		/* Entry action for state 'Standby'. */
		timerService.setTimer(this, 1, 500l, false);
		garageDoor.door().setBlock(sensorOutput.activity);
		actuator.setIsTriggered(controller.actuator().getTriggered());
		controller.actuator().setFinished(actuator.device().getFunctionFinished());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_ControllerComponent_off() {
		/* Entry action for state 'off'. */
		getController().raiseOff();
	}
	
	/* Entry action for state 'Sensor_Component'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component() {
		/* Entry action for state 'Sensor_Component'. */
		timerService.setTimer(this, 2, 500l, false);
		sensorOutput.setActivity(sensor.status().getActivity());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_SensorComponent_off() {
		/* Entry action for state 'off'. */
		getSensor().raiseOff();
	}
	
	/* Entry action for state 'Initialize_Network_Component'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component() {
		/* Entry action for state 'Initialize_Network_Component'. */
		getWiFi().enter();
	}
	
	/* Entry action for state 'Network_Component'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component() {
		/* Entry action for state 'Network_Component'. */
		timerService.setTimer(this, 3, 500l, false);
		setWiFi_connection(wiFi.getConnection());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_NetworkComponent_off() {
		/* Entry action for state 'off'. */
		getWiFi().raiseOff();
	}
	
	/* Entry action for state 'Initialize_Power_Component'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component() {
		/* Entry action for state 'Initialize_Power_Component'. */
		power.setKilowatt(power_input);
	}
	
	/* Entry action for state 'Power_Consumption_Updates'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates() {
		/* Entry action for state 'Power_Consumption_Updates'. */
		timerService.setTimer(this, 4, 500l, false);
		power.device().setIsOn(system.isOn);
		power.setKilowatt(power_input);
		setPower_total(power.getKWh());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off() {
		/* Entry action for state 'off'. */
		getPower().raiseOff();
	}
	
	/* Entry action for state 'Temperature_Updates'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates() {
		/* Entry action for state 'Temperature_Updates'. */
		timerService.setTimer(this, 5, 500l, false);
		setTemp_value(temp.heat().getLevel());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_off() {
		/* Entry action for state 'off'. */
		temp.device().setIsOn(system.isOn);
	}
	
	/* Exit action for state 'on'. */
	private void exitAction_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on() {
		/* Exit action for state 'on'. */
		timerService.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Standby'. */
	private void exitAction_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby() {
		/* Exit action for state 'Standby'. */
		timerService.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'Sensor_Component'. */
	private void exitAction_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component() {
		/* Exit action for state 'Sensor_Component'. */
		timerService.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction_SmartGarageDoorSystem_IoT_Template_SensorComponent_off() {
		/* Exit action for state 'off'. */
		getSensor().raiseOn();
	}
	
	/* Exit action for state 'Network_Component'. */
	private void exitAction_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component() {
		/* Exit action for state 'Network_Component'. */
		timerService.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction_SmartGarageDoorSystem_IoT_Template_NetworkComponent_off() {
		/* Exit action for state 'off'. */
		getWiFi().raiseOn();
	}
	
	/* Exit action for state 'Power_Consumption_Updates'. */
	private void exitAction_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates() {
		/* Exit action for state 'Power_Consumption_Updates'. */
		timerService.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off() {
		/* Exit action for state 'off'. */
		getPower().raiseOn();
	}
	
	/* Exit action for state 'Temperature_Updates'. */
	private void exitAction_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates() {
		/* Exit action for state 'Temperature_Updates'. */
		timerService.unsetTimer(this, 5);
	}
	
	/* 'default' enter sequence for state IoT_Template */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_default() {
		/* 'default' enter sequence for state IoT_Template */
		enterSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_default();
		enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_default();
		enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_default();
		enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_default();
		enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_default();
		enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_default();
		enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_default();
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_off_default() {
		/* 'default' enter sequence for state off */
		entryAction_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_off();
		stateVector[0] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_OFF;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state on */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on_default() {
		/* 'default' enter sequence for state on */
		entryAction_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on();
		stateVector[0] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_ON;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state Actuator_isON */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON_default() {
		/* 'default' enter sequence for state Actuator_isON */
		entryAction_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON();
		enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__default();
	}
	
	/* 'default' enter sequence for state Actuator_Standby */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Actuator_Standby_default() {
		/* 'default' enter sequence for state Actuator_Standby */
		stateVector[1] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__ACTUATOR_STANDBY;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state Close */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Close_default() {
		/* 'default' enter sequence for state Close */
		entryAction_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Close();
		stateVector[1] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__CLOSE;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state Open */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Open_default() {
		/* 'default' enter sequence for state Open */
		entryAction_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Open();
		stateVector[1] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__OPEN;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_off();
		stateVector[1] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_OFF;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state Controller_Component_isON */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON_default() {
		/* 'default' enter sequence for state Controller_Component_isON */
		entryAction_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON();
		enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__default();
	}
	
	/* 'default' enter sequence for state Controller_Processing */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Controller_Processing_default() {
		/* 'default' enter sequence for state Controller_Processing */
		entryAction_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Controller_Processing();
		stateVector[2] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__CONTROLLER_PROCESSING;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state Standby */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby_default() {
		/* 'default' enter sequence for state Standby */
		entryAction_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby();
		stateVector[2] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__STANDBY;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction_SmartGarageDoorSystem_IoT_Template_ControllerComponent_off();
		stateVector[2] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_OFF;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state Sensor_Component_isON */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON_default() {
		/* 'default' enter sequence for state Sensor_Component_isON */
		enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__default();
	}
	
	/* 'default' enter sequence for state Sensor_Component */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component_default() {
		/* 'default' enter sequence for state Sensor_Component */
		entryAction_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component();
		stateVector[3] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON__SENSOR_MONITORING__SENSOR_COMPONENT;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction_SmartGarageDoorSystem_IoT_Template_SensorComponent_off();
		stateVector[3] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_OFF;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state Initialize_Network_Component */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component_default() {
		/* 'default' enter sequence for state Initialize_Network_Component */
		entryAction_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component();
		enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__default();
	}
	
	/* 'default' enter sequence for state Network_Component */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component_default() {
		/* 'default' enter sequence for state Network_Component */
		entryAction_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component();
		stateVector[4] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT__RECEIVING_NETWORK_CONNECTION_UPDATES__NETWORK_COMPONENT;
		stateConfVectorPosition = 4;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction_SmartGarageDoorSystem_IoT_Template_NetworkComponent_off();
		stateVector[4] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_OFF;
		stateConfVectorPosition = 4;
	}
	
	/* 'default' enter sequence for state Initialize_Power_Component */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component_default() {
		/* 'default' enter sequence for state Initialize_Power_Component */
		entryAction_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component();
		enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__default();
	}
	
	/* 'default' enter sequence for state Power_Consumption_Updates */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates_default() {
		/* 'default' enter sequence for state Power_Consumption_Updates */
		entryAction_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates();
		stateVector[5] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT__RECEIVING_UPDATES_FROM_POWER_COMPONENT__POWER_CONSUMPTION_UPDATES;
		stateConfVectorPosition = 5;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off();
		stateVector[5] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_OFF;
		stateConfVectorPosition = 5;
	}
	
	/* 'default' enter sequence for state Initialize_DeviceTemp_Component */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component_default() {
		/* 'default' enter sequence for state Initialize_DeviceTemp_Component */
		enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__default();
	}
	
	/* 'default' enter sequence for state Temperature_Updates */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates_default() {
		/* 'default' enter sequence for state Temperature_Updates */
		entryAction_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates();
		stateVector[6] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT__RECEIVING_UPDATES_FROM_DEVICETEMP_COMPONENT__TEMPERATURE_UPDATES;
		stateConfVectorPosition = 6;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_off_default() {
		/* 'default' enter sequence for state off */
		entryAction_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_off();
		stateVector[6] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_OFF;
		stateConfVectorPosition = 6;
	}
	
	/* 'default' enter sequence for region SmartGarageDoorSystem */
	private void enterSequence_SmartGarageDoorSystem_default() {
		/* 'default' enter sequence for region SmartGarageDoorSystem */
		react_SmartGarageDoorSystem__entry_Default();
	}
	
	/* 'default' enter sequence for region DeviceSwitchStatus */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_default() {
		/* 'default' enter sequence for region DeviceSwitchStatus */
		react_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus__entry_Default();
	}
	
	/* 'default' enter sequence for region ActuatorComponent */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_default() {
		/* 'default' enter sequence for region ActuatorComponent */
		react_SmartGarageDoorSystem_IoT_Template_ActuatorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region <DoorStatus> */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__default() {
		/* 'default' enter sequence for region <DoorStatus> */
		react_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus___entry_Default();
	}
	
	/* 'default' enter sequence for region ControllerComponent */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_default() {
		/* 'default' enter sequence for region ControllerComponent */
		react_SmartGarageDoorSystem_IoT_Template_ControllerComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region <Controller_Receiving_and_Sending_Updates> */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__default() {
		/* 'default' enter sequence for region <Controller_Receiving_and_Sending_Updates> */
		react_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates___entry_Default();
	}
	
	/* 'default' enter sequence for region SensorComponent */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_default() {
		/* 'default' enter sequence for region SensorComponent */
		react_SmartGarageDoorSystem_IoT_Template_SensorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region <Sensor_Monitoring> */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__default() {
		/* 'default' enter sequence for region <Sensor_Monitoring> */
		react_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring___entry_Default();
	}
	
	/* 'default' enter sequence for region NetworkComponent */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_default() {
		/* 'default' enter sequence for region NetworkComponent */
		react_SmartGarageDoorSystem_IoT_Template_NetworkComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region <Receiving_Network_Connection_Updates> */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__default() {
		/* 'default' enter sequence for region <Receiving_Network_Connection_Updates> */
		react_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates___entry_Default();
	}
	
	/* 'default' enter sequence for region PowerCalculatorComponent */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_default() {
		/* 'default' enter sequence for region PowerCalculatorComponent */
		react_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region <Receiving_Updates_From_Power_Component> */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__default() {
		/* 'default' enter sequence for region <Receiving_Updates_From_Power_Component> */
		react_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component___entry_Default();
	}
	
	/* 'default' enter sequence for region trackingDeviceTemperature */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_default() {
		/* 'default' enter sequence for region trackingDeviceTemperature */
		react_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature__entry_Default();
	}
	
	/* 'default' enter sequence for region <Receiving_Updates_from_DeviceTemp_Component> */
	private void enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__default() {
		/* 'default' enter sequence for region <Receiving_Updates_from_DeviceTemp_Component> */
		react_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component___entry_Default();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_off() {
		/* Default exit sequence for state off */
		stateVector[0] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state on */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on() {
		/* Default exit sequence for state on */
		stateVector[0] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 0;
		exitAction_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on();
	}
	
	/* Default exit sequence for state Actuator_isON */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON() {
		/* Default exit sequence for state Actuator_isON */
		exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus_();
		stateVector[1] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 1;
	}
	
	/* Default exit sequence for state Actuator_Standby */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Actuator_Standby() {
		/* Default exit sequence for state Actuator_Standby */
		stateVector[1] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON;
		stateConfVectorPosition = 1;
	}
	
	/* Default exit sequence for state Close */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Close() {
		/* Default exit sequence for state Close */
		stateVector[1] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON;
		stateConfVectorPosition = 1;
	}
	
	/* Default exit sequence for state Open */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Open() {
		/* Default exit sequence for state Open */
		stateVector[1] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON;
		stateConfVectorPosition = 1;
	}
	
	/* Default exit sequence for state off */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_off() {
		/* Default exit sequence for state off */
		stateVector[1] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 1;
	}
	
	/* Default exit sequence for state Controller_Component_isON */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON() {
		/* Default exit sequence for state Controller_Component_isON */
		exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates_();
		stateVector[2] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 2;
	}
	
	/* Default exit sequence for state Controller_Processing */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Controller_Processing() {
		/* Default exit sequence for state Controller_Processing */
		stateVector[2] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON;
		stateConfVectorPosition = 2;
	}
	
	/* Default exit sequence for state Standby */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby() {
		/* Default exit sequence for state Standby */
		stateVector[2] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON;
		stateConfVectorPosition = 2;
		exitAction_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_off() {
		/* Default exit sequence for state off */
		stateVector[2] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 2;
	}
	
	/* Default exit sequence for state Sensor_Component_isON */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON() {
		/* Default exit sequence for state Sensor_Component_isON */
		exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring_();
		stateVector[3] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 3;
	}
	
	/* Default exit sequence for state Sensor_Component */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component() {
		/* Default exit sequence for state Sensor_Component */
		stateVector[3] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON;
		stateConfVectorPosition = 3;
		exitAction_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_off() {
		/* Default exit sequence for state off */
		stateVector[3] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 3;
		exitAction_SmartGarageDoorSystem_IoT_Template_SensorComponent_off();
	}
	
	/* Default exit sequence for state Initialize_Network_Component */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component() {
		/* Default exit sequence for state Initialize_Network_Component */
		exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates_();
		stateVector[4] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 4;
	}
	
	/* Default exit sequence for state Network_Component */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component() {
		/* Default exit sequence for state Network_Component */
		stateVector[4] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT;
		stateConfVectorPosition = 4;
		exitAction_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_off() {
		/* Default exit sequence for state off */
		stateVector[4] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 4;
		exitAction_SmartGarageDoorSystem_IoT_Template_NetworkComponent_off();
	}
	
	/* Default exit sequence for state Initialize_Power_Component */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component() {
		/* Default exit sequence for state Initialize_Power_Component */
		exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component_();
		stateVector[5] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 5;
	}
	
	/* Default exit sequence for state Power_Consumption_Updates */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates() {
		/* Default exit sequence for state Power_Consumption_Updates */
		stateVector[5] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT;
		stateConfVectorPosition = 5;
		exitAction_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off() {
		/* Default exit sequence for state off */
		stateVector[5] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 5;
		exitAction_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off();
	}
	
	/* Default exit sequence for state Initialize_DeviceTemp_Component */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component() {
		/* Default exit sequence for state Initialize_DeviceTemp_Component */
		exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component_();
		stateVector[6] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 6;
	}
	
	/* Default exit sequence for state Temperature_Updates */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates() {
		/* Default exit sequence for state Temperature_Updates */
		stateVector[6] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT;
		stateConfVectorPosition = 6;
		exitAction_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_off() {
		/* Default exit sequence for state off */
		stateVector[6] = State.SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE;
		stateConfVectorPosition = 6;
	}
	
	/* Default exit sequence for region SmartGarageDoorSystem */
	private void exitSequence_SmartGarageDoorSystem() {
		/* Default exit sequence for region SmartGarageDoorSystem */
		switch (stateVector[0]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_OFF:
			exitSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_off();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_DEVICESWITCHSTATUS_ON:
			exitSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on();
			break;
		default:
			break;
		}
		switch (stateVector[1]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__ACTUATOR_STANDBY:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Actuator_Standby();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__CLOSE:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Close();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__OPEN:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Open();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_OFF:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_off();
			break;
		default:
			break;
		}
		switch (stateVector[2]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__CONTROLLER_PROCESSING:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Controller_Processing();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__STANDBY:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_OFF:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_off();
			break;
		default:
			break;
		}
		switch (stateVector[3]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON:
			exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON__SENSOR_MONITORING__SENSOR_COMPONENT:
			exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_OFF:
			exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_off();
			break;
		default:
			break;
		}
		switch (stateVector[4]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT:
			exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT__RECEIVING_NETWORK_CONNECTION_UPDATES__NETWORK_COMPONENT:
			exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_OFF:
			exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_off();
			break;
		default:
			break;
		}
		switch (stateVector[5]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT:
			exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT__RECEIVING_UPDATES_FROM_POWER_COMPONENT__POWER_CONSUMPTION_UPDATES:
			exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_OFF:
			exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off();
			break;
		default:
			break;
		}
		switch (stateVector[6]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT:
			exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT__RECEIVING_UPDATES_FROM_DEVICETEMP_COMPONENT__TEMPERATURE_UPDATES:
			exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_OFF:
			exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_off();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region <DoorStatus> */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus_() {
		/* Default exit sequence for region <DoorStatus> */
		switch (stateVector[1]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__ACTUATOR_STANDBY:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Actuator_Standby();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__CLOSE:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Close();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_ACTUATORCOMPONENT_ACTUATOR_ISON__DOORSTATUS__OPEN:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Open();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region <Controller_Receiving_and_Sending_Updates> */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates_() {
		/* Default exit sequence for region <Controller_Receiving_and_Sending_Updates> */
		switch (stateVector[2]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__CONTROLLER_PROCESSING:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Controller_Processing();
			break;
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_CONTROLLERCOMPONENT_CONTROLLER_COMPONENT_ISON__CONTROLLER_RECEIVING_AND_SENDING_UPDATES__STANDBY:
			exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region <Sensor_Monitoring> */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring_() {
		/* Default exit sequence for region <Sensor_Monitoring> */
		switch (stateVector[3]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_SENSORCOMPONENT_SENSOR_COMPONENT_ISON__SENSOR_MONITORING__SENSOR_COMPONENT:
			exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region <Receiving_Network_Connection_Updates> */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates_() {
		/* Default exit sequence for region <Receiving_Network_Connection_Updates> */
		switch (stateVector[4]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_NETWORKCOMPONENT_INITIALIZE_NETWORK_COMPONENT__RECEIVING_NETWORK_CONNECTION_UPDATES__NETWORK_COMPONENT:
			exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region <Receiving_Updates_From_Power_Component> */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component_() {
		/* Default exit sequence for region <Receiving_Updates_From_Power_Component> */
		switch (stateVector[5]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_POWERCALCULATORCOMPONENT_INITIALIZE_POWER_COMPONENT__RECEIVING_UPDATES_FROM_POWER_COMPONENT__POWER_CONSUMPTION_UPDATES:
			exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region <Receiving_Updates_from_DeviceTemp_Component> */
	private void exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component_() {
		/* Default exit sequence for region <Receiving_Updates_from_DeviceTemp_Component> */
		switch (stateVector[6]) {
		case SMARTGARAGEDOORSYSTEM_IOT_TEMPLATE_TRACKINGDEVICETEMPERATURE_INITIALIZE_DEVICETEMP_COMPONENT__RECEIVING_UPDATES_FROM_DEVICETEMP_COMPONENT__TEMPERATURE_UPDATES:
			exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_ActuatorComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getActuator().enter();
		enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus___entry_Default() {
		/* Default react sequence for initial entry  */
		getGarageDoor().enter();
		enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Actuator_Standby_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_ControllerComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getController().enter();
		enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates___entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_SensorComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getSensor().enter();
		enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring___entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_NetworkComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getWiFi().enter();
		enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates___entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getPower().enter();
		enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component___entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature__entry_Default() {
		/* Default react sequence for initial entry  */
		getTemp().enter();
		enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component___entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SmartGarageDoorSystem__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SmartGarageDoorSystem_IoT_Template_default();
	}
	
	private long smartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (system.on) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_off();
				enterSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on_react(long transitioned_before) {
		/* The reactions of state on. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (system.off) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on();
				enterSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_off_default();
				transitioned_after = 0l;
			} else {
				if (timeEvents[0]) {
					exitSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on();
					timeEvents[0] = false;
					enterSequence_SmartGarageDoorSystem_IoT_Template_DeviceSwitchStatus_on_default();
					transitioned_after = 0l;
				}
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON_react(long transitioned_before) {
		/* The reactions of state Actuator_isON. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (system.off) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON();
				enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_off_default();
				transitioned_after = 1l;
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Actuator_Standby_react(long transitioned_before) {
		/* The reactions of state Actuator_Standby. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (((system.active_actuator) && (!(getGarageDoor().door().getDoor_closed())))) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Actuator_Standby();
				enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Close_default();
				smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON_react(1l);
				transitioned_after = 1l;
			} else {
				if (((system.active_actuator) && (getGarageDoor().door().getDoor_closed()))) {
					exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Actuator_Standby();
					enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Open_default();
					smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON_react(1l);
					transitioned_after = 1l;
				}
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			if ((getActuator().getIsTriggered() && !(getActuator().device().getFunctionFinished()))) {
				system.raiseActive_actuator();
			}
			transitioned_after = smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Close_react(long transitioned_before) {
		/* The reactions of state Close. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (system.deactive_actuator) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Close();
				enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Actuator_Standby_default();
				smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON_react(1l);
				transitioned_after = 1l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Open_react(long transitioned_before) {
		/* The reactions of state Open. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (system.deactive_actuator) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Open();
				enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON__DoorStatus__Actuator_Standby_default();
				smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON_react(1l);
				transitioned_after = 1l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = smartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_ActuatorComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (system.on) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_off();
				enterSequence_SmartGarageDoorSystem_IoT_Template_ActuatorComponent_Actuator_isON_default();
				transitioned_after = 1l;
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON_react(long transitioned_before) {
		/* The reactions of state Controller_Component_isON. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (system.off) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON();
				enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_off_default();
				transitioned_after = 2l;
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Controller_Processing_react(long transitioned_before) {
		/* The reactions of state Controller_Processing. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Controller_Processing();
			enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby_default();
			smartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON_react(2l);
			transitioned_after = 2l;
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = smartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby_react(long transitioned_before) {
		/* The reactions of state Standby. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (active_controller) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby();
				enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Controller_Processing_default();
				smartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON_react(2l);
				transitioned_after = 2l;
			} else {
				if (timeEvents[1]) {
					exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby();
					timeEvents[1] = false;
					enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON__Controller_Receiving_and_Sending_Updates__Standby_default();
					smartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON_react(2l);
					transitioned_after = 2l;
				}
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = smartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_ControllerComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (system.on) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_off();
				enterSequence_SmartGarageDoorSystem_IoT_Template_ControllerComponent_Controller_Component_isON_default();
				transitioned_after = 2l;
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON_react(long transitioned_before) {
		/* The reactions of state Sensor_Component_isON. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (system.off) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON();
				enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_off_default();
				transitioned_after = 3l;
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component_react(long transitioned_before) {
		/* The reactions of state Sensor_Component. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (timeEvents[2]) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component();
				timeEvents[2] = false;
				enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON__Sensor_Monitoring__Sensor_Component_default();
				smartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON_react(3l);
				transitioned_after = 3l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = smartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_SensorComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (system.on) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_off();
				enterSequence_SmartGarageDoorSystem_IoT_Template_SensorComponent_Sensor_Component_isON_default();
				transitioned_after = 3l;
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component_react(long transitioned_before) {
		/* The reactions of state Initialize_Network_Component. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<4l) {
			if ((system.off || system.disconnect_network)) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component();
				enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_off_default();
				transitioned_after = 4l;
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component_react(long transitioned_before) {
		/* The reactions of state Network_Component. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<4l) {
			if (timeEvents[3]) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component();
				timeEvents[3] = false;
				enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component__Receiving_Network_Connection_Updates__Network_Component_default();
				smartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component_react(4l);
				transitioned_after = 4l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = smartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_NetworkComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<4l) {
			if ((system.on || system.connect_network)) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_off();
				enterSequence_SmartGarageDoorSystem_IoT_Template_NetworkComponent_Initialize_Network_Component_default();
				transitioned_after = 4l;
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component_react(long transitioned_before) {
		/* The reactions of state Initialize_Power_Component. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<5l) {
			if (system.off) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component();
				enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off_default();
				transitioned_after = 5l;
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates_react(long transitioned_before) {
		/* The reactions of state Power_Consumption_Updates. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<5l) {
			if (timeEvents[4]) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates();
				timeEvents[4] = false;
				enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component__Receiving_Updates_From_Power_Component__Power_Consumption_Updates_default();
				smartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component_react(5l);
				transitioned_after = 5l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = smartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<5l) {
			if (system.on) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_off();
				enterSequence_SmartGarageDoorSystem_IoT_Template_PowerCalculatorComponent_Initialize_Power_Component_default();
				transitioned_after = 5l;
			}
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component_react(long transitioned_before) {
		/* The reactions of state Initialize_DeviceTemp_Component. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<6l) {
			if (system.off) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component();
				enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_off_default();
				transitioned_after = 6l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates_react(long transitioned_before) {
		/* The reactions of state Temperature_Updates. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<6l) {
			if (timeEvents[5]) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates();
				timeEvents[5] = false;
				enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component__Receiving_Updates_from_DeviceTemp_Component__Temperature_Updates_default();
				smartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component_react(6l);
				transitioned_after = 6l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = smartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long smartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<6l) {
			if (system.on) {
				exitSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_off();
				enterSequence_SmartGarageDoorSystem_IoT_Template_trackingDeviceTemperature_Initialize_DeviceTemp_Component_default();
				transitioned_after = 6l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		}
		return transitioned_after;
	}
	
	/* Can be used by the client code to trigger a run to completion step without raising an event. */
	public synchronized void triggerWithoutEvent() {
		runCycle();
	}
}
