/* Generated by itemis CREATE code generator. */
package smarthub.java;

import com.yakindu.core.IEventDriven;
import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import com.yakindu.core.rx.Observer;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import smarthub.java.Actuator_Component_2;
import smarthub.java.DeviceTemp_Component;
import smarthub.java.FireAlarm_Unit;
import smarthub.java.Network_Component;
import smarthub.java.Power_Component;
import smarthub.java.Sensor_Component_Fire;

public class SmartFireSystem implements ITimed, IEventDriven {
	public static class System {
		private SmartFireSystem parent;
		
		public System(SmartFireSystem parent) {
			this.parent = parent;
		}
		private boolean on;
		
		
		public void raiseOn() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					on = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean off;
		
		
		public void raiseOff() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					off = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean connect_network;
		
		
		public void raiseConnect_network() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					connect_network = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean disconnect_network;
		
		
		public void raiseDisconnect_network() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					disconnect_network = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean sensor_active;
		
		
		public void raiseSensor_active() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					sensor_active = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean isOn;
		
		public synchronized boolean getIsOn() {
			synchronized(parent) {
				return isOn;
			}
		}
		
		public void setIsOn(boolean value) {
			synchronized(parent) {
				this.isOn = value;
			}
		}
		
		private boolean alarm_status;
		
		public synchronized boolean getAlarm_status() {
			synchronized(parent) {
				return alarm_status;
			}
		}
		
		public void setAlarm_status(boolean value) {
			synchronized(parent) {
				this.alarm_status = value;
			}
		}
		
	}
	
	public static class SensorInput {
		private SmartFireSystem parent;
		
		public SensorInput(SmartFireSystem parent) {
			this.parent = parent;
		}
		private boolean reset;
		
		
		public void raiseReset() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					reset = true;
				});
				parent.runCycle();
			}
		}
		
		private long smoke_detection_time;
		
		public synchronized long getSmoke_detection_time() {
			synchronized(parent) {
				return smoke_detection_time;
			}
		}
		
		public void setSmoke_detection_time(long value) {
			synchronized(parent) {
				this.smoke_detection_time = value;
			}
		}
		
		private long flame_detection_time;
		
		public synchronized long getFlame_detection_time() {
			synchronized(parent) {
				return flame_detection_time;
			}
		}
		
		public void setFlame_detection_time(long value) {
			synchronized(parent) {
				this.flame_detection_time = value;
			}
		}
		
		private long heat_detection_time;
		
		public synchronized long getHeat_detection_time() {
			synchronized(parent) {
				return heat_detection_time;
			}
		}
		
		public void setHeat_detection_time(long value) {
			synchronized(parent) {
				this.heat_detection_time = value;
			}
		}
		
	}
	
	public static class SensorOutput {
		private SmartFireSystem parent;
		
		public SensorOutput(SmartFireSystem parent) {
			this.parent = parent;
		}
		private boolean activity;
		
		public synchronized boolean getActivity() {
			synchronized(parent) {
				return activity;
			}
		}
		
		public void setActivity(boolean value) {
			synchronized(parent) {
				this.activity = value;
			}
		}
		
		private String detected;
		
		public synchronized String getDetected() {
			synchronized(parent) {
				return detected;
			}
		}
		
		public void setDetected(String value) {
			synchronized(parent) {
				this.detected = value;
			}
		}
		
	}
	
	public static class FlameSensorOutput {
		private SmartFireSystem parent;
		
		public FlameSensorOutput(SmartFireSystem parent) {
			this.parent = parent;
		}
		private long counter;
		
		public synchronized long getCounter() {
			synchronized(parent) {
				return counter;
			}
		}
		
		public void setCounter(long value) {
			synchronized(parent) {
				this.counter = value;
			}
		}
		
		private boolean activity;
		
		public synchronized boolean getActivity() {
			synchronized(parent) {
				return activity;
			}
		}
		
		public void setActivity(boolean value) {
			synchronized(parent) {
				this.activity = value;
			}
		}
		
	}
	
	public static class HeatSensorOutput {
		private SmartFireSystem parent;
		
		public HeatSensorOutput(SmartFireSystem parent) {
			this.parent = parent;
		}
		private long counter;
		
		public synchronized long getCounter() {
			synchronized(parent) {
				return counter;
			}
		}
		
		public void setCounter(long value) {
			synchronized(parent) {
				this.counter = value;
			}
		}
		
		private boolean activity;
		
		public synchronized boolean getActivity() {
			synchronized(parent) {
				return activity;
			}
		}
		
		public void setActivity(boolean value) {
			synchronized(parent) {
				this.activity = value;
			}
		}
		
	}
	
	public static class SmokeSensorOutput {
		private SmartFireSystem parent;
		
		public SmokeSensorOutput(SmartFireSystem parent) {
			this.parent = parent;
		}
		private long counter;
		
		public synchronized long getCounter() {
			synchronized(parent) {
				return counter;
			}
		}
		
		public void setCounter(long value) {
			synchronized(parent) {
				this.counter = value;
			}
		}
		
		private boolean activity;
		
		public synchronized boolean getActivity() {
			synchronized(parent) {
				return activity;
			}
		}
		
		public void setActivity(boolean value) {
			synchronized(parent) {
				this.activity = value;
			}
		}
		
	}
	
	protected System system;
	
	protected SensorInput sensorInput;
	
	protected SensorOutput sensorOutput;
	
	protected FlameSensorOutput flameSensorOutput;
	
	protected HeatSensorOutput heatSensorOutput;
	
	protected SmokeSensorOutput smokeSensorOutput;
	
	public enum State {
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_INACTIVE,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_ACTIVE,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_ONSTANDBY_,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__DEVICE_ACTUATED_,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_OFF_,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_OFF,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_INACTIVE,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_ACTIVE,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_INACTIVE,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_ACTIVE,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_INACTIVE,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_ACTIVE,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT_,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT___RECEIVING_NETWORK_CONNECTION_UPDATES___NETWORK_CONNECTION_UPDATES_,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT_OFF,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT_,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT___RECEIVING_UPDATES_FROM_POWER_COMPONENT___POWER_CONSUMPTION_UPDATES_,
		_SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT_OFF,
		$NULLSTATE$
	};
	
	private final State[] stateVector = new State[7];
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[3];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean fireAlarm_Alarm_on;
	private boolean fireAlarm_Alarm_off;
	private boolean flameSensor_overThreshold;
	private boolean flameSensor_underThreshold;
	private boolean smokeSensor_overThreshold;
	private boolean smokeSensor_underThreshold;
	private boolean heatSensor_overThreshold;
	private boolean heatSensor_underThreshold;
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		synchronized(SmartFireSystem.this) {
			return isExecuting;
		}
	}
	
	protected void setIsExecuting(boolean value) {
		synchronized(SmartFireSystem.this) {
			this.isExecuting = value;
		}
	}
	private long stateConfVectorPosition;
	
	protected long getStateConfVectorPosition() {
		synchronized(SmartFireSystem.this) {
			return stateConfVectorPosition;
		}
	}
	
	protected void setStateConfVectorPosition(long value) {
		synchronized(SmartFireSystem.this) {
			this.stateConfVectorPosition = value;
		}
	}
	public SmartFireSystem() {
		system = new System(this);
		sensorInput = new SensorInput(this);
		sensorOutput = new SensorOutput(this);
		flameSensorOutput = new FlameSensorOutput(this);
		heatSensorOutput = new HeatSensorOutput(this);
		smokeSensorOutput = new SmokeSensorOutput(this);
		for (int i = 0; i < 7; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		/* Default init sequence for statechart SmartFireSystem */
		setActuator(null);
		setFlameSensor(null);
		setSmokeSensor(null);
		setHeatSensor(null);
		setWiFi(null);
		setPower(null);
		setTemp(null);
		setFireAlarm(null);
		setMessage("test");
		setWiFi_connection(false);
		setTemp_value(50l);
		setPower_input(20l);
		setPower_total(0l);
		setPower_required(10l);
		system.setIsOn(false);
		system.setAlarm_status(false);
		sensorInput.setSmoke_detection_time(9l);
		sensorInput.setFlame_detection_time(11l);
		sensorInput.setHeat_detection_time(10l);
		sensorOutput.setActivity(false);
		sensorOutput.setDetected("");
		flameSensorOutput.setCounter(0l);
		flameSensorOutput.setActivity(false);
		heatSensorOutput.setCounter(0l);
		heatSensorOutput.setActivity(false);
		smokeSensorOutput.setCounter(0l);
		smokeSensorOutput.setActivity(false);
		
		isExecuting = false;
	}
	
	public synchronized void enter() {
		/* Activates the state machine. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		/* Default enter sequence for statechart SmartFireSystem */
		enterSequence__SmartFiresystem__default();
		isExecuting = false;
	}
	
	public synchronized void exit() {
		/* Deactivates the state machine. */
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		/* Default exit sequence for statechart SmartFireSystem */
		exitSequence__SmartFiresystem_();
		stateVector[0] = State.$NULLSTATE$;
		stateVector[1] = State.$NULLSTATE$;
		stateVector[2] = State.$NULLSTATE$;
		stateVector[3] = State.$NULLSTATE$;
		stateVector[4] = State.$NULLSTATE$;
		stateVector[5] = State.$NULLSTATE$;
		stateVector[6] = State.$NULLSTATE$;
		stateConfVectorPosition = 6;
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$||stateVector[1] != State.$NULLSTATE$||stateVector[2] != State.$NULLSTATE$||stateVector[3] != State.$NULLSTATE$||stateVector[4] != State.$NULLSTATE$||stateVector[5] != State.$NULLSTATE$||stateVector[6] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	private void clearInEvents() {
		system.on = false;
		system.off = false;
		system.connect_network = false;
		system.disconnect_network = false;
		system.sensor_active = false;
		sensorInput.reset = false;
		fireAlarm_Alarm_on = false;
		fireAlarm_Alarm_off = false;
		flameSensor_overThreshold = false;
		flameSensor_underThreshold = false;
		smokeSensor_overThreshold = false;
		smokeSensor_underThreshold = false;
		heatSensor_overThreshold = false;
		heatSensor_underThreshold = false;
		timeEvents[0] = false;
		timeEvents[1] = false;
		timeEvents[2] = false;
	}
	
	private void microStep() {
		long transitioned = -1l;
		stateConfVectorPosition = 0l;
		switch (stateVector[0]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_INACTIVE:
			transitioned = _SmartFiresystem__SmartFireSystem_DeviceStatus_inactive_react(transitioned);
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_ACTIVE:
			transitioned = _SmartFiresystem__SmartFireSystem_DeviceStatus_active_react(transitioned);
			break;
		default:
			break;
		}
		if (getStateConfVectorPosition()<1l) {
			switch (stateVector[1]) {
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_ONSTANDBY_:
				transitioned = _SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_OnStandby__react(transitioned);
				break;
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__DEVICE_ACTUATED_:
				transitioned = _SmartFiresystem__SmartFireSystem_ActuatorComponent__Device_Actuated__react(transitioned);
				break;
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_OFF_:
				transitioned = _SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off__react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<2l) {
			switch (stateVector[2]) {
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_OFF:
				transitioned = _SmartFiresystem__SmartFireSystem_SensorComponent_off_react(transitioned);
				break;
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_INACTIVE:
				transitioned = _SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_inactive_react(transitioned);
				break;
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_ACTIVE:
				transitioned = _SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_active_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<3l) {
			switch (stateVector[3]) {
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_INACTIVE:
				transitioned = _SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_inactive_react(transitioned);
				break;
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_ACTIVE:
				transitioned = _SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_active_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<4l) {
			switch (stateVector[4]) {
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_INACTIVE:
				transitioned = _SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_inactive_react(transitioned);
				break;
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_ACTIVE:
				transitioned = _SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_active_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<5l) {
			switch (stateVector[5]) {
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT___RECEIVING_NETWORK_CONNECTION_UPDATES___NETWORK_CONNECTION_UPDATES_:
				transitioned = _SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates__react(transitioned);
				break;
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT_OFF:
				transitioned = _SmartFiresystem__SmartFireSystem_NetworkComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<6l) {
			switch (stateVector[6]) {
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT___RECEIVING_UPDATES_FROM_POWER_COMPONENT___POWER_CONSUMPTION_UPDATES_:
				_SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates__react(transitioned);
				break;
			case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT_OFF:
				_SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
	}
	
	private void runCycle() {
		/* Performs a 'run to completion' step. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		nextEvent();
		do { 
			microStep();
			clearInEvents();
		} while (nextEvent());
		isExecuting = false;
	}
	
	protected boolean nextEvent() {
		if(!inEventQueue.isEmpty()) {
			inEventQueue.poll().run();
			return true;
		}
		return false;
	}
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM:
			return stateVector[0].ordinal() >= State.
					_SMARTFIRESYSTEM__SMARTFIRESYSTEM.ordinal()&& stateVector[0].ordinal() <= State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT_OFF.ordinal();
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_INACTIVE:
			return stateVector[0] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_INACTIVE;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_ACTIVE:
			return stateVector[0] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_ACTIVE;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_ONSTANDBY_:
			return stateVector[1] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_ONSTANDBY_;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__DEVICE_ACTUATED_:
			return stateVector[1] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__DEVICE_ACTUATED_;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_OFF_:
			return stateVector[1] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_OFF_;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_OFF:
			return stateVector[2] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_OFF;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON:
			return stateVector[2].ordinal() >= State.
					_SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON.ordinal()&& stateVector[2].ordinal() <= State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_ACTIVE.ordinal();
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_INACTIVE:
			return stateVector[2] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_INACTIVE;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_ACTIVE:
			return stateVector[2] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_ACTIVE;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_INACTIVE:
			return stateVector[3] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_INACTIVE;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_ACTIVE:
			return stateVector[3] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_ACTIVE;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_INACTIVE:
			return stateVector[4] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_INACTIVE;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_ACTIVE:
			return stateVector[4] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_ACTIVE;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT_:
			return stateVector[5].ordinal() >= State.
					_SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT_.ordinal()&& stateVector[5].ordinal() <= State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT___RECEIVING_NETWORK_CONNECTION_UPDATES___NETWORK_CONNECTION_UPDATES_.ordinal();
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT___RECEIVING_NETWORK_CONNECTION_UPDATES___NETWORK_CONNECTION_UPDATES_:
			return stateVector[5] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT___RECEIVING_NETWORK_CONNECTION_UPDATES___NETWORK_CONNECTION_UPDATES_;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT_OFF:
			return stateVector[5] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT_OFF;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT_:
			return stateVector[6].ordinal() >= State.
					_SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT_.ordinal()&& stateVector[6].ordinal() <= State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT___RECEIVING_UPDATES_FROM_POWER_COMPONENT___POWER_CONSUMPTION_UPDATES_.ordinal();
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT___RECEIVING_UPDATES_FROM_POWER_COMPONENT___POWER_CONSUMPTION_UPDATES_:
			return stateVector[6] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT___RECEIVING_UPDATES_FROM_POWER_COMPONENT___POWER_CONSUMPTION_UPDATES_;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT_OFF:
			return stateVector[6] == State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT_OFF;
		default:
			return false;
		}
	}
	
	public synchronized void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public synchronized void raiseTimeEvent(int eventID) {
		inEventQueue.add(() -> {
			timeEvents[eventID] = true;
		});
		runCycle();
	}
	
	public System system() {
		return system;
	}
	
	public SensorInput sensorInput() {
		return sensorInput;
	}
	
	public SensorOutput sensorOutput() {
		return sensorOutput;
	}
	
	public FlameSensorOutput flameSensorOutput() {
		return flameSensorOutput;
	}
	
	public HeatSensorOutput heatSensorOutput() {
		return heatSensorOutput;
	}
	
	public SmokeSensorOutput smokeSensorOutput() {
		return smokeSensorOutput;
	}
	
	
	protected void raiseFireAlarm_Alarm_on() {
		synchronized(SmartFireSystem.this) {
			inEventQueue.add(() -> {
				fireAlarm_Alarm_on = true;
			});
			runCycle();
		}
	}
	
	protected void raiseFireAlarm_Alarm_off() {
		synchronized(SmartFireSystem.this) {
			inEventQueue.add(() -> {
				fireAlarm_Alarm_off = true;
			});
			runCycle();
		}
	}
	
	protected void raiseFlameSensor_overThreshold() {
		synchronized(SmartFireSystem.this) {
			inEventQueue.add(() -> {
				flameSensor_overThreshold = true;
			});
			runCycle();
		}
	}
	
	protected void raiseFlameSensor_underThreshold() {
		synchronized(SmartFireSystem.this) {
			inEventQueue.add(() -> {
				flameSensor_underThreshold = true;
			});
			runCycle();
		}
	}
	
	protected void raiseSmokeSensor_overThreshold() {
		synchronized(SmartFireSystem.this) {
			inEventQueue.add(() -> {
				smokeSensor_overThreshold = true;
			});
			runCycle();
		}
	}
	
	protected void raiseSmokeSensor_underThreshold() {
		synchronized(SmartFireSystem.this) {
			inEventQueue.add(() -> {
				smokeSensor_underThreshold = true;
			});
			runCycle();
		}
	}
	
	protected void raiseHeatSensor_overThreshold() {
		synchronized(SmartFireSystem.this) {
			inEventQueue.add(() -> {
				heatSensor_overThreshold = true;
			});
			runCycle();
		}
	}
	
	protected void raiseHeatSensor_underThreshold() {
		synchronized(SmartFireSystem.this) {
			inEventQueue.add(() -> {
				heatSensor_underThreshold = true;
			});
			runCycle();
		}
	}
	
	private Actuator_Component_2 actuator;
	
	public synchronized Actuator_Component_2 getActuator() {
		synchronized(SmartFireSystem.this) {
			return actuator;
		}
	}
	
	public void setActuator(Actuator_Component_2 value) {
		synchronized(SmartFireSystem.this) {
			this.actuator = value;
		}
	}
	
	private Sensor_Component_Fire flameSensor;
	
	private Observer<Void> FlameSensor_overThreshold_observer = new Observer<Void>() {
		@Override
		public void next(Void value) {
			raiseFlameSensor_overThreshold();
		}
	};
	
	private Observer<Void> FlameSensor_underThreshold_observer = new Observer<Void>() {
		@Override
		public void next(Void value) {
			raiseFlameSensor_underThreshold();
		}
	};
	
	
	public synchronized Sensor_Component_Fire getFlameSensor() {
		synchronized(SmartFireSystem.this) {
			return flameSensor;
		}
	}
	
	public void setFlameSensor(Sensor_Component_Fire value) {
		synchronized(SmartFireSystem.this) {
			if (this.flameSensor != null) {
				this.flameSensor.getOverThreshold().unsubscribe(FlameSensor_overThreshold_observer);
				this.flameSensor.getUnderThreshold().unsubscribe(FlameSensor_underThreshold_observer);
			}
			
			this.flameSensor = value;
			
			if (this.flameSensor != null) {
				this.flameSensor.getOverThreshold().subscribe(FlameSensor_overThreshold_observer);
				this.flameSensor.getUnderThreshold().subscribe(FlameSensor_underThreshold_observer);
			}
		}
	}
	
	private Sensor_Component_Fire smokeSensor;
	
	private Observer<Void> SmokeSensor_overThreshold_observer = new Observer<Void>() {
		@Override
		public void next(Void value) {
			raiseSmokeSensor_overThreshold();
		}
	};
	
	private Observer<Void> SmokeSensor_underThreshold_observer = new Observer<Void>() {
		@Override
		public void next(Void value) {
			raiseSmokeSensor_underThreshold();
		}
	};
	
	
	public synchronized Sensor_Component_Fire getSmokeSensor() {
		synchronized(SmartFireSystem.this) {
			return smokeSensor;
		}
	}
	
	public void setSmokeSensor(Sensor_Component_Fire value) {
		synchronized(SmartFireSystem.this) {
			if (this.smokeSensor != null) {
				this.smokeSensor.getOverThreshold().unsubscribe(SmokeSensor_overThreshold_observer);
				this.smokeSensor.getUnderThreshold().unsubscribe(SmokeSensor_underThreshold_observer);
			}
			
			this.smokeSensor = value;
			
			if (this.smokeSensor != null) {
				this.smokeSensor.getOverThreshold().subscribe(SmokeSensor_overThreshold_observer);
				this.smokeSensor.getUnderThreshold().subscribe(SmokeSensor_underThreshold_observer);
			}
		}
	}
	
	private Sensor_Component_Fire heatSensor;
	
	private Observer<Void> HeatSensor_overThreshold_observer = new Observer<Void>() {
		@Override
		public void next(Void value) {
			raiseHeatSensor_overThreshold();
		}
	};
	
	private Observer<Void> HeatSensor_underThreshold_observer = new Observer<Void>() {
		@Override
		public void next(Void value) {
			raiseHeatSensor_underThreshold();
		}
	};
	
	
	public synchronized Sensor_Component_Fire getHeatSensor() {
		synchronized(SmartFireSystem.this) {
			return heatSensor;
		}
	}
	
	public void setHeatSensor(Sensor_Component_Fire value) {
		synchronized(SmartFireSystem.this) {
			if (this.heatSensor != null) {
				this.heatSensor.getOverThreshold().unsubscribe(HeatSensor_overThreshold_observer);
				this.heatSensor.getUnderThreshold().unsubscribe(HeatSensor_underThreshold_observer);
			}
			
			this.heatSensor = value;
			
			if (this.heatSensor != null) {
				this.heatSensor.getOverThreshold().subscribe(HeatSensor_overThreshold_observer);
				this.heatSensor.getUnderThreshold().subscribe(HeatSensor_underThreshold_observer);
			}
		}
	}
	
	private Network_Component wiFi;
	
	public synchronized Network_Component getWiFi() {
		synchronized(SmartFireSystem.this) {
			return wiFi;
		}
	}
	
	public void setWiFi(Network_Component value) {
		synchronized(SmartFireSystem.this) {
			this.wiFi = value;
		}
	}
	
	private Power_Component power;
	
	public synchronized Power_Component getPower() {
		synchronized(SmartFireSystem.this) {
			return power;
		}
	}
	
	public void setPower(Power_Component value) {
		synchronized(SmartFireSystem.this) {
			this.power = value;
		}
	}
	
	private DeviceTemp_Component temp;
	
	public synchronized DeviceTemp_Component getTemp() {
		synchronized(SmartFireSystem.this) {
			return temp;
		}
	}
	
	public void setTemp(DeviceTemp_Component value) {
		synchronized(SmartFireSystem.this) {
			this.temp = value;
		}
	}
	
	private FireAlarm_Unit fireAlarm;
	
	private Observer<Void> FireAlarm_Alarm_on_observer = new Observer<Void>() {
		@Override
		public void next(Void value) {
			raiseFireAlarm_Alarm_on();
		}
	};
	
	private Observer<Void> FireAlarm_Alarm_off_observer = new Observer<Void>() {
		@Override
		public void next(Void value) {
			raiseFireAlarm_Alarm_off();
		}
	};
	
	
	public synchronized FireAlarm_Unit getFireAlarm() {
		synchronized(SmartFireSystem.this) {
			return fireAlarm;
		}
	}
	
	public void setFireAlarm(FireAlarm_Unit value) {
		synchronized(SmartFireSystem.this) {
			if (this.fireAlarm != null) {
				this.fireAlarm.alarm().getOn().unsubscribe(FireAlarm_Alarm_on_observer);
				this.fireAlarm.alarm().getOff().unsubscribe(FireAlarm_Alarm_off_observer);
			}
			
			this.fireAlarm = value;
			
			if (this.fireAlarm != null) {
				this.fireAlarm.alarm().getOn().subscribe(FireAlarm_Alarm_on_observer);
				this.fireAlarm.alarm().getOff().subscribe(FireAlarm_Alarm_off_observer);
			}
		}
	}
	
	private String message;
	
	public synchronized String getMessage() {
		synchronized(SmartFireSystem.this) {
			return message;
		}
	}
	
	public void setMessage(String value) {
		synchronized(SmartFireSystem.this) {
			this.message = value;
		}
	}
	
	private boolean wiFi_connection;
	
	public synchronized boolean getWiFi_connection() {
		synchronized(SmartFireSystem.this) {
			return wiFi_connection;
		}
	}
	
	public void setWiFi_connection(boolean value) {
		synchronized(SmartFireSystem.this) {
			this.wiFi_connection = value;
		}
	}
	
	private long temp_value;
	
	public synchronized long getTemp_value() {
		synchronized(SmartFireSystem.this) {
			return temp_value;
		}
	}
	
	public void setTemp_value(long value) {
		synchronized(SmartFireSystem.this) {
			this.temp_value = value;
		}
	}
	
	private long power_input;
	
	public synchronized long getPower_input() {
		synchronized(SmartFireSystem.this) {
			return power_input;
		}
	}
	
	public void setPower_input(long value) {
		synchronized(SmartFireSystem.this) {
			this.power_input = value;
		}
	}
	
	private long power_total;
	
	public synchronized long getPower_total() {
		synchronized(SmartFireSystem.this) {
			return power_total;
		}
	}
	
	public void setPower_total(long value) {
		synchronized(SmartFireSystem.this) {
			this.power_total = value;
		}
	}
	
	private long power_required;
	
	public synchronized long getPower_required() {
		synchronized(SmartFireSystem.this) {
			return power_required;
		}
	}
	
	public void setPower_required(long value) {
		synchronized(SmartFireSystem.this) {
			this.power_required = value;
		}
	}
	
	/* Entry action for state 'inactive'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_DeviceStatus_inactive() {
		/* Entry action for state 'inactive'. */
		fireAlarm.sensors().setTriggerSignal_received(false);
	}
	
	/* Entry action for state 'active'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_DeviceStatus_active() {
		/* Entry action for state 'active'. */
		timerService.setTimer(this, 0, (1l * 1000l), true);
		fireAlarm.sensors().setTriggerSignal_received(true);
	}
	
	/* Entry action for state '<Actuator_OnStandby>'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_OnStandby_() {
		/* Entry action for state '<Actuator_OnStandby>'. */
		actuator.power().setDeviceInput(power_input);
		actuator.setIsTriggered(false);
	}
	
	/* Entry action for state '<Device_Actuated>'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_ActuatorComponent__Device_Actuated_() {
		/* Entry action for state '<Device_Actuated>'. */
		actuator.setIsTriggered(true);
	}
	
	/* Entry action for state '<Actuator_off>'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off_() {
		/* Entry action for state '<Actuator_off>'. */
		getActuator().raiseOff();
		actuator.power().setRequired(power_required);
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_off() {
		/* Entry action for state 'off'. */
		getFlameSensor().raiseOff();
		getSmokeSensor().raiseOff();
		getHeatSensor().raiseOff();
	}
	
	/* Entry action for state 'on'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on() {
		/* Entry action for state 'on'. */
		getFlameSensor().raiseOn();
		getSmokeSensor().raiseOn();
		getHeatSensor().raiseOn();
	}
	
	/* Entry action for state 'inactive'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_inactive() {
		/* Entry action for state 'inactive'. */
		flameSensorOutput.setActivity(false);
	}
	
	/* Entry action for state 'active'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_active() {
		/* Entry action for state 'active'. */
		system.raiseSensor_active();
		flameSensorOutput.setActivity(true);
	}
	
	/* Entry action for state 'inactive'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_inactive() {
		/* Entry action for state 'inactive'. */
		smokeSensorOutput.setActivity(false);
	}
	
	/* Entry action for state 'active'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_active() {
		/* Entry action for state 'active'. */
		system.raiseSensor_active();
		smokeSensorOutput.setActivity(true);
	}
	
	/* Entry action for state 'inactive'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_inactive() {
		/* Entry action for state 'inactive'. */
		heatSensorOutput.setActivity(false);
	}
	
	/* Entry action for state 'active'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_active() {
		/* Entry action for state 'active'. */
		system.raiseSensor_active();
		heatSensorOutput.setActivity(true);
	}
	
	/* Entry action for state '<Network_Connection_Updates>'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates_() {
		/* Entry action for state '<Network_Connection_Updates>'. */
		timerService.setTimer(this, 1, 500l, false);
		setWiFi_connection(wiFi.getConnection());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_NetworkComponent_off() {
		/* Entry action for state 'off'. */
		getWiFi().raiseOff();
	}
	
	/* Entry action for state '<Power_Consumption_Updates>'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates_() {
		/* Entry action for state '<Power_Consumption_Updates>'. */
		timerService.setTimer(this, 2, 500l, false);
		power.device().setIsOn(system.isOn);
		power.setKilowatt(power_input);
		setPower_total(power.getKWh());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off() {
		/* Entry action for state 'off'. */
		getPower().raiseOff();
	}
	
	/* Exit action for state 'active'. */
	private void exitAction__SmartFiresystem__SmartFireSystem_DeviceStatus_active() {
		/* Exit action for state 'active'. */
		timerService.unsetTimer(this, 0);
	}
	
	/* Exit action for state '<Actuator_off>'. */
	private void exitAction__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off_() {
		/* Exit action for state '<Actuator_off>'. */
		getActuator().raiseOn();
	}
	
	/* Exit action for state '<Network_Connection_Updates>'. */
	private void exitAction__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates_() {
		/* Exit action for state '<Network_Connection_Updates>'. */
		timerService.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartFiresystem__SmartFireSystem_NetworkComponent_off() {
		/* Exit action for state 'off'. */
		getWiFi().raiseOn();
	}
	
	/* Exit action for state '<Power_Consumption_Updates>'. */
	private void exitAction__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates_() {
		/* Exit action for state '<Power_Consumption_Updates>'. */
		timerService.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off() {
		/* Exit action for state 'off'. */
		getPower().raiseOn();
	}
	
	/* 'default' enter sequence for state SmartFireSystem */
	private void enterSequence__SmartFiresystem__SmartFireSystem_default() {
		/* 'default' enter sequence for state SmartFireSystem */
		enterSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_default();
		enterSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent_default();
		enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_default();
		enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent_default();
		enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_default();
	}
	
	/* 'default' enter sequence for state inactive */
	private void enterSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_inactive_default() {
		/* 'default' enter sequence for state inactive */
		entryAction__SmartFiresystem__SmartFireSystem_DeviceStatus_inactive();
		stateVector[0] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_INACTIVE;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state active */
	private void enterSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_active_default() {
		/* 'default' enter sequence for state active */
		entryAction__SmartFiresystem__SmartFireSystem_DeviceStatus_active();
		stateVector[0] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_ACTIVE;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state <Actuator_OnStandby> */
	private void enterSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_OnStandby__default() {
		/* 'default' enter sequence for state <Actuator_OnStandby> */
		entryAction__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_OnStandby_();
		stateVector[1] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_ONSTANDBY_;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state <Device_Actuated> */
	private void enterSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Device_Actuated__default() {
		/* 'default' enter sequence for state <Device_Actuated> */
		entryAction__SmartFiresystem__SmartFireSystem_ActuatorComponent__Device_Actuated_();
		stateVector[1] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__DEVICE_ACTUATED_;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state <Actuator_off> */
	private void enterSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off__default() {
		/* 'default' enter sequence for state <Actuator_off> */
		entryAction__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off_();
		stateVector[1] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_OFF_;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_off();
		stateVector[2] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_OFF;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state on */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_default() {
		/* 'default' enter sequence for state on */
		entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on();
		enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_default();
		enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_default();
		enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_default();
	}
	
	/* 'default' enter sequence for state inactive */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_inactive_default() {
		/* 'default' enter sequence for state inactive */
		entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_inactive();
		stateVector[2] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_INACTIVE;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state active */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_active_default() {
		/* 'default' enter sequence for state active */
		entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_active();
		stateVector[2] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_ACTIVE;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state inactive */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_inactive_default() {
		/* 'default' enter sequence for state inactive */
		entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_inactive();
		stateVector[3] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_INACTIVE;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state active */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_active_default() {
		/* 'default' enter sequence for state active */
		entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_active();
		stateVector[3] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_ACTIVE;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state inactive */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_inactive_default() {
		/* 'default' enter sequence for state inactive */
		entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_inactive();
		stateVector[4] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_INACTIVE;
		stateConfVectorPosition = 4;
	}
	
	/* 'default' enter sequence for state active */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_active_default() {
		/* 'default' enter sequence for state active */
		entryAction__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_active();
		stateVector[4] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_ACTIVE;
		stateConfVectorPosition = 4;
	}
	
	/* 'default' enter sequence for state <Initialize_Network_Component> */
	private void enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component__default() {
		/* 'default' enter sequence for state <Initialize_Network_Component> */
		enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates__default();
	}
	
	/* 'default' enter sequence for state <Network_Connection_Updates> */
	private void enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates__default() {
		/* 'default' enter sequence for state <Network_Connection_Updates> */
		entryAction__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates_();
		stateVector[5] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT___RECEIVING_NETWORK_CONNECTION_UPDATES___NETWORK_CONNECTION_UPDATES_;
		stateConfVectorPosition = 5;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction__SmartFiresystem__SmartFireSystem_NetworkComponent_off();
		stateVector[5] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT_OFF;
		stateConfVectorPosition = 5;
	}
	
	/* 'default' enter sequence for state <Initialize_Power_Component> */
	private void enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component__default() {
		/* 'default' enter sequence for state <Initialize_Power_Component> */
		enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component__default();
	}
	
	/* 'default' enter sequence for state <Power_Consumption_Updates> */
	private void enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates__default() {
		/* 'default' enter sequence for state <Power_Consumption_Updates> */
		entryAction__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates_();
		stateVector[6] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT___RECEIVING_UPDATES_FROM_POWER_COMPONENT___POWER_CONSUMPTION_UPDATES_;
		stateConfVectorPosition = 6;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off();
		stateVector[6] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT_OFF;
		stateConfVectorPosition = 6;
	}
	
	/* 'default' enter sequence for region <SmartFiresystem> */
	private void enterSequence__SmartFiresystem__default() {
		/* 'default' enter sequence for region <SmartFiresystem> */
		react__SmartFiresystem___entry_Default();
	}
	
	/* 'default' enter sequence for region DeviceStatus */
	private void enterSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_default() {
		/* 'default' enter sequence for region DeviceStatus */
		react__SmartFiresystem__SmartFireSystem_DeviceStatus__entry_Default();
	}
	
	/* 'default' enter sequence for region ActuatorComponent */
	private void enterSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent_default() {
		/* 'default' enter sequence for region ActuatorComponent */
		react__SmartFiresystem__SmartFireSystem_ActuatorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region SensorComponent */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_default() {
		/* 'default' enter sequence for region SensorComponent */
		react__SmartFiresystem__SmartFireSystem_SensorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region FlameSensor */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_default() {
		/* 'default' enter sequence for region FlameSensor */
		react__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor__entry_Default();
	}
	
	/* 'default' enter sequence for region SmokeSensor */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_default() {
		/* 'default' enter sequence for region SmokeSensor */
		react__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor__entry_Default();
	}
	
	/* 'default' enter sequence for region HeatSensor */
	private void enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_default() {
		/* 'default' enter sequence for region HeatSensor */
		react__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor__entry_Default();
	}
	
	/* 'default' enter sequence for region NetworkComponent */
	private void enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent_default() {
		/* 'default' enter sequence for region NetworkComponent */
		react__SmartFiresystem__SmartFireSystem_NetworkComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region <Receiving_Network_Connection_Updates> */
	private void enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates__default() {
		/* 'default' enter sequence for region <Receiving_Network_Connection_Updates> */
		react__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___entry_Default();
	}
	
	/* 'default' enter sequence for region PowerCalculatorComponent */
	private void enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_default() {
		/* 'default' enter sequence for region PowerCalculatorComponent */
		react__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region <Receiving_Updates_From_Power_Component> */
	private void enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component__default() {
		/* 'default' enter sequence for region <Receiving_Updates_From_Power_Component> */
		react__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___entry_Default();
	}
	
	/* Default exit sequence for state inactive */
	private void exitSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_inactive() {
		/* Default exit sequence for state inactive */
		stateVector[0] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state active */
	private void exitSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_active() {
		/* Default exit sequence for state active */
		stateVector[0] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateConfVectorPosition = 0;
		exitAction__SmartFiresystem__SmartFireSystem_DeviceStatus_active();
	}
	
	/* Default exit sequence for state <Actuator_OnStandby> */
	private void exitSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_OnStandby_() {
		/* Default exit sequence for state <Actuator_OnStandby> */
		stateVector[1] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateConfVectorPosition = 1;
	}
	
	/* Default exit sequence for state <Device_Actuated> */
	private void exitSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Device_Actuated_() {
		/* Default exit sequence for state <Device_Actuated> */
		stateVector[1] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateConfVectorPosition = 1;
	}
	
	/* Default exit sequence for state <Actuator_off> */
	private void exitSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off_() {
		/* Default exit sequence for state <Actuator_off> */
		stateVector[1] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateConfVectorPosition = 1;
		exitAction__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_off() {
		/* Default exit sequence for state off */
		stateVector[2] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateConfVectorPosition = 2;
	}
	
	/* Default exit sequence for state on */
	private void exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on() {
		/* Default exit sequence for state on */
		exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor();
		exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor();
		exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor();
		stateVector[2] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateVector[3] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateVector[4] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateConfVectorPosition = 4;
	}
	
	/* Default exit sequence for state inactive */
	private void exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_inactive() {
		/* Default exit sequence for state inactive */
		stateVector[2] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON;
		stateConfVectorPosition = 2;
	}
	
	/* Default exit sequence for state active */
	private void exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_active() {
		/* Default exit sequence for state active */
		stateVector[2] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON;
		stateConfVectorPosition = 2;
	}
	
	/* Default exit sequence for state inactive */
	private void exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_inactive() {
		/* Default exit sequence for state inactive */
		stateVector[3] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON;
		stateConfVectorPosition = 3;
	}
	
	/* Default exit sequence for state active */
	private void exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_active() {
		/* Default exit sequence for state active */
		stateVector[3] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON;
		stateConfVectorPosition = 3;
	}
	
	/* Default exit sequence for state inactive */
	private void exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_inactive() {
		/* Default exit sequence for state inactive */
		stateVector[4] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON;
		stateConfVectorPosition = 4;
	}
	
	/* Default exit sequence for state active */
	private void exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_active() {
		/* Default exit sequence for state active */
		stateVector[4] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON;
		stateConfVectorPosition = 4;
	}
	
	/* Default exit sequence for state <Initialize_Network_Component> */
	private void exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component_() {
		/* Default exit sequence for state <Initialize_Network_Component> */
		exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates_();
		stateVector[5] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateConfVectorPosition = 5;
	}
	
	/* Default exit sequence for state <Network_Connection_Updates> */
	private void exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates_() {
		/* Default exit sequence for state <Network_Connection_Updates> */
		stateVector[5] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT_;
		stateConfVectorPosition = 5;
		exitAction__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent_off() {
		/* Default exit sequence for state off */
		stateVector[5] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateConfVectorPosition = 5;
		exitAction__SmartFiresystem__SmartFireSystem_NetworkComponent_off();
	}
	
	/* Default exit sequence for state <Initialize_Power_Component> */
	private void exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component_() {
		/* Default exit sequence for state <Initialize_Power_Component> */
		exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component_();
		stateVector[6] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateConfVectorPosition = 6;
	}
	
	/* Default exit sequence for state <Power_Consumption_Updates> */
	private void exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates_() {
		/* Default exit sequence for state <Power_Consumption_Updates> */
		stateVector[6] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT_;
		stateConfVectorPosition = 6;
		exitAction__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off() {
		/* Default exit sequence for state off */
		stateVector[6] = State._SMARTFIRESYSTEM__SMARTFIRESYSTEM;
		stateConfVectorPosition = 6;
		exitAction__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off();
	}
	
	/* Default exit sequence for region <SmartFiresystem> */
	private void exitSequence__SmartFiresystem_() {
		/* Default exit sequence for region <SmartFiresystem> */
		switch (stateVector[0]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_INACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_inactive();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_DEVICESTATUS_ACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_active();
			break;
		default:
			break;
		}
		switch (stateVector[1]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_ONSTANDBY_:
			exitSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_OnStandby_();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__DEVICE_ACTUATED_:
			exitSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Device_Actuated_();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_ACTUATORCOMPONENT__ACTUATOR_OFF_:
			exitSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off_();
			break;
		default:
			break;
		}
		switch (stateVector[2]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_OFF:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_off();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_INACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_inactive();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_ACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_active();
			break;
		default:
			break;
		}
		switch (stateVector[3]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_INACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_inactive();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_ACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_active();
			break;
		default:
			break;
		}
		switch (stateVector[4]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_INACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_inactive();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_ACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_active();
			break;
		default:
			break;
		}
		switch (stateVector[5]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT_:
			exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component_();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT___RECEIVING_NETWORK_CONNECTION_UPDATES___NETWORK_CONNECTION_UPDATES_:
			exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates_();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT_OFF:
			exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent_off();
			break;
		default:
			break;
		}
		switch (stateVector[6]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT_:
			exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component_();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT___RECEIVING_UPDATES_FROM_POWER_COMPONENT___POWER_CONSUMPTION_UPDATES_:
			exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates_();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT_OFF:
			exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region FlameSensor */
	private void exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor() {
		/* Default exit sequence for region FlameSensor */
		switch (stateVector[2]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_INACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_inactive();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_FLAMESENSOR_ACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_active();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region SmokeSensor */
	private void exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor() {
		/* Default exit sequence for region SmokeSensor */
		switch (stateVector[3]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_INACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_inactive();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_SMOKESENSOR_ACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_active();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region HeatSensor */
	private void exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor() {
		/* Default exit sequence for region HeatSensor */
		switch (stateVector[4]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_INACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_inactive();
			break;
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_SENSORCOMPONENT_ON_HEATSENSOR_ACTIVE:
			exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_active();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region <Receiving_Network_Connection_Updates> */
	private void exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates_() {
		/* Default exit sequence for region <Receiving_Network_Connection_Updates> */
		switch (stateVector[5]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_NETWORKCOMPONENT__INITIALIZE_NETWORK_COMPONENT___RECEIVING_NETWORK_CONNECTION_UPDATES___NETWORK_CONNECTION_UPDATES_:
			exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region <Receiving_Updates_From_Power_Component> */
	private void exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component_() {
		/* Default exit sequence for region <Receiving_Updates_From_Power_Component> */
		switch (stateVector[6]) {
		case _SMARTFIRESYSTEM__SMARTFIRESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT___RECEIVING_UPDATES_FROM_POWER_COMPONENT___POWER_CONSUMPTION_UPDATES_:
			exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartFiresystem__SmartFireSystem_DeviceStatus__entry_Default() {
		/* Default react sequence for initial entry  */
		getFireAlarm().enter();
		enterSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_inactive_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartFiresystem__SmartFireSystem_ActuatorComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getActuator().enter();
		enterSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartFiresystem__SmartFireSystem_SensorComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getFlameSensor().enter();
		getSmokeSensor().enter();
		getHeatSensor().enter();
		enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_inactive_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_inactive_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_inactive_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartFiresystem__SmartFireSystem_NetworkComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getWiFi().enter();
		enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getPower().enter();
		enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartFiresystem___entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartFiresystem__SmartFireSystem_default();
	}
	
	private long _SmartFiresystem__SmartFireSystem_DeviceStatus_inactive_react(long transitioned_before) {
		/* The reactions of state inactive. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (system.sensor_active) {
				exitSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_inactive();
				enterSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_active_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_DeviceStatus_active_react(long transitioned_before) {
		/* The reactions of state active. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (((timeEvents[0]) && (((!(flameSensorOutput.getActivity()) && !(smokeSensorOutput.getActivity())) && !(heatSensorOutput.getActivity()))))) {
				exitSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_active();
				timeEvents[0] = false;
				enterSequence__SmartFiresystem__SmartFireSystem_DeviceStatus_inactive_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_OnStandby__react(long transitioned_before) {
		/* The reactions of state <Actuator_OnStandby>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (fireAlarm_Alarm_on) {
				exitSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_OnStandby_();
				enterSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Device_Actuated__default();
				transitioned_after = 1l;
			} else {
				if (system.off) {
					exitSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_OnStandby_();
					enterSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off__default();
					transitioned_after = 1l;
				}
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_ActuatorComponent__Device_Actuated__react(long transitioned_before) {
		/* The reactions of state <Device_Actuated>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (fireAlarm_Alarm_off) {
				exitSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Device_Actuated_();
				enterSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_OnStandby__default();
				transitioned_after = 1l;
			} else {
				if (system.off) {
					exitSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Device_Actuated_();
					enterSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off__default();
					transitioned_after = 1l;
				}
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off__react(long transitioned_before) {
		/* The reactions of state <Actuator_off>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (system.on) {
				exitSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_off_();
				enterSequence__SmartFiresystem__SmartFireSystem_ActuatorComponent__Actuator_OnStandby__default();
				transitioned_after = 1l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_SensorComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (system.on) {
				exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_off();
				enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_default();
				transitioned_after = 2l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_SensorComponent_on_react(long transitioned_before) {
		/* The reactions of state on. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (system.off) {
				exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on();
				enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_off_default();
				transitioned_after = 4l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_inactive_react(long transitioned_before) {
		/* The reactions of state inactive. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (flameSensor_overThreshold) {
				exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_inactive();
				enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_active_default();
				transitioned_after = 2l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_active_react(long transitioned_before) {
		/* The reactions of state active. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (flameSensor_underThreshold) {
				exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_active();
				enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_FlameSensor_inactive_default();
				transitioned_after = 2l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_inactive_react(long transitioned_before) {
		/* The reactions of state inactive. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (smokeSensor_overThreshold) {
				exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_inactive();
				enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_active_default();
				transitioned_after = 3l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_active_react(long transitioned_before) {
		/* The reactions of state active. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (smokeSensor_underThreshold) {
				exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_active();
				enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_SmokeSensor_inactive_default();
				transitioned_after = 3l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_inactive_react(long transitioned_before) {
		/* The reactions of state inactive. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<4l) {
			if (heatSensor_overThreshold) {
				exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_inactive();
				enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_active_default();
				_SmartFiresystem__SmartFireSystem_SensorComponent_on_react(2l);
				transitioned_after = 4l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = _SmartFiresystem__SmartFireSystem_SensorComponent_on_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_active_react(long transitioned_before) {
		/* The reactions of state active. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<4l) {
			if (heatSensor_underThreshold) {
				exitSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_active();
				enterSequence__SmartFiresystem__SmartFireSystem_SensorComponent_on_HeatSensor_inactive_default();
				_SmartFiresystem__SmartFireSystem_SensorComponent_on_react(2l);
				transitioned_after = 4l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = _SmartFiresystem__SmartFireSystem_SensorComponent_on_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component__react(long transitioned_before) {
		/* The reactions of state <Initialize_Network_Component>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<5l) {
			if ((system.off || system.disconnect_network)) {
				exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component_();
				enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent_off_default();
				transitioned_after = 5l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates__react(long transitioned_before) {
		/* The reactions of state <Network_Connection_Updates>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<5l) {
			if (timeEvents[1]) {
				exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates_();
				timeEvents[1] = false;
				enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component___Receiving_Network_Connection_Updates___Network_Connection_Updates__default();
				_SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component__react(5l);
				transitioned_after = 5l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = _SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component__react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_NetworkComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<5l) {
			if ((system.on || system.connect_network)) {
				exitSequence__SmartFiresystem__SmartFireSystem_NetworkComponent_off();
				enterSequence__SmartFiresystem__SmartFireSystem_NetworkComponent__Initialize_Network_Component__default();
				transitioned_after = 5l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component__react(long transitioned_before) {
		/* The reactions of state <Initialize_Power_Component>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<6l) {
			if (system.off) {
				exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component_();
				enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off_default();
				transitioned_after = 6l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates__react(long transitioned_before) {
		/* The reactions of state <Power_Consumption_Updates>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<6l) {
			if (timeEvents[2]) {
				exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates_();
				timeEvents[2] = false;
				enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component___Receiving_Updates_From_Power_Component___Power_Consumption_Updates__default();
				_SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component__react(6l);
				transitioned_after = 6l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = _SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component__react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<6l) {
			if (system.on) {
				exitSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent_off();
				enterSequence__SmartFiresystem__SmartFireSystem_PowerCalculatorComponent__Initialize_Power_Component__default();
				transitioned_after = 6l;
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		}
		return transitioned_after;
	}
	
	/* Can be used by the client code to trigger a run to completion step without raising an event. */
	public synchronized void triggerWithoutEvent() {
		runCycle();
	}
}
